### PR TITLE
Add categories in rc/

### LINKED ISSUE #2783: Add categories in rc/
How about adding sub-directories to [rc] scripts?

Inside [core], [base], [extra], add `languages`, `tools`, `linters`, etc.

[rc]: https://github.com/mawww/kakoune/tree/master/rc
[core]: https://github.com/mawww/kakoune/tree/master/rc/core
[base]: https://github.com/mawww/kakoune/tree/master/rc/base
[extra]: https://github.com/mawww/kakoune/tree/master/rc/extra

### PR DESCRIPTION
**Pull request by alexherbo2**
- [rc/](https://github.com/alexherbo2/kakoune/tree/rc-categories/rc)
  - [detection/](https://github.com/alexherbo2/kakoune/tree/rc-categories/rc/detection)
  - [file-type/](https://github.com/alexherbo2/kakoune/tree/rc-categories/rc/file-type)
  - [tools/](https://github.com/alexherbo2/kakoune/tree/rc-categories/rc/tools)
  - [windowing/](https://github.com/alexherbo2/kakoune/tree/rc-categories/rc/windowing)

I renamed:
- `tools/git-tools.kak` → `tools/git.kak`
- `windowing/x11-repl.kak` → `windowing/x11/repl.kak`
- `windowing/tmux-repl.kak` → `windowing/tmux/repl.kak`

I’m not sure about:
- ~~[file.kak](https://github.com/alexherbo2/kakoune/blob/rc-categories/rc/tools/file.kak) in [tools](https://github.com/alexherbo2/kakoune/blob/rc-categories/rc/tools)~~
- ~~[modeline.kak](https://github.com/alexherbo2/kakoune/blob/rc-categories/rc/tools/modeline.kak) in [tools](https://github.com/alexherbo2/kakoune/blob/rc-categories/rc/tools)~~
- ~~REPLs in [windowing](https://github.com/alexherbo2/kakoune/tree/rc-categories/rc/windowing)~~
- ~~Some include syntax highlighting and commands; for example [man.kak](https://github.com/alexherbo2/kakoune/blob/rc-categories/rc/tools/man.kak) or [editorconfig.kak](https://github.com/alexherbo2/kakoune/blob/rc-categories/rc/tools/editorconfig.kak)~~
- ~~Some don’t feel like tools – they are internal to Kakoune; for example [autorestore.kak](https://github.com/alexherbo2/kakoune/blob/rc-categories/rc/tools/autorestore.kak)~~

Closes #2783

### CODE REVIEW

**Comment by mawww** [comment]
the kakoune option is named `filetype`, so I think we should not use an alternate spelling `file-type` here.

man.kak should go in tools/ IMHO, man.kak highlighting is for buffers opened by the man command.

file.kak, editorconfig.kak and modeline.kak are all option detection mechanisms, so maybe a fourth `detection` category would make sense.

I am not sure what to do with REPLs.

**Comment by alexherbo2** [comment]
`autorestore.kak` is a tool?

**Comment by laelath** [comment]
It might make sense to merge the REPLs with their relevant terminal support. For now windowing seems like a fine place for the REPLs to me.

**Comment by mawww** [comment]
You need to update the indentation tests to source the new path for their filetype support script.

**Comment by mawww** [comment]
For autorestore.kak, we can put it in tools for now, I think once provides/requires is merged in we will likely move it to some kind of `lib/` directory with other internal helpers.

**Pull request closed without merging**
