### PR TITLE
Improve comment-line command

### LINKED ISSUE #2156: multi-line selection should be commented on the same level with `comment-line`
Let's use this code snippet:

```python
1: def main():
2:     for i in range(5):
3:         print(i)
4:     print('done')
```

--------------

<details>
<summary>Case 1: Select everything with <code>%</code>, run <code>comment-line</code>.</summary>

Expected:

```python
1: # def main():
2: #     for i in range(5):
3: #         print(i)
4: #     print('done')
```

Actual:

```python
1: # def main():
2:     # for i in range(5):
3:         # print(i)
4:     # print('done')
```
</details>

-------------

<details>
<summary>Case 2: Select lines 2-4, run <code>comment-line</code>.</summary>

Expected: 

```python
1: def main():
2:     # for i in range(5):
3:     #     print(i)
4:     # print('done')
```

Actual:

```python
1: def main():
2:     # for i in range(5):
3:         # print(i)
4:     # print('done')
```
</details>

-----------------

I was hoping to make a PR instead of an issue, but I got stuck at coming up with a smart way to make this selection.

Currently the selection is being trimmed with `<a-s>gi<a-l>`, but it leads to the "Actual" behavior that I want to avoid. So far I was thinking to also trim the selection with `<a-s>gi`, but then to align cursors with the most _left_ one - kind of like the opposite of `&` operator. But there is no such operator, as far as I can see... Maybe there is another way to achieve what I want?

### LINKED ISSUE #2161: The selected lines should be uncommented only if all of them were commented
Suppose you have the following snippet:

```yaml
abc:
    # def: ha
    eg: bla
```

You want to comment it all, so you select everything with `%` and execute `comment-line` command.

Expected:

```yaml
# abc:
#     # def: ha
#     eg: bla
```

Actual:

```yaml
abc:
    def: ha
    eg: bla
```

I tried to come up with a solution in order to make PR, but stumbled upon a couple of roadblocks. Below is the snippet I could get to myself, and it has a couple of issues:

1. `Z` and `z` don't seem to have any effect within the command, so I cannot test whether all lines are commented with `<a-K>` and then safely restore the selection.
2. The `execute-keys <a-K>\A\Q%opt{comment_line}\E\h?<ret>` doesn't seem to raise an error when there are no lines left, so the code doesn't go into `catch` block, even though when testing manually I do see a red error message in the bottom saying that "no selections remaining".

Please point me in the right direction, or make your own PR, I don't mind as long as I can get the functionality in `master` :)

```kak
define-command comment-line -docstring '(un)comment selected lines using line comments' %{
    %sh{
        if [ -z "${kak_opt_comment_line}" ]; then
            echo "fail \"The 'comment_line' option is empty, could not comment the line\""
        fi
    }
    evaluate-commands -draft %{
        # Select the content of the lines, without indentation
        execute-keys <a-s>gi<a-l>

        try %{
            # Keep non-empty lines and save the selection
            execute-keys <a-K>\A\s*\z<ret>Z

            try %{
                # See if there are any uncommented lines in the selection
                execute-keys <a-K>\A\Q%opt{comment_line}\E\h?<ret>

                # There are uncommented lines, so restore the selection and comment everything
                set-register '"' "%opt{comment_line} "
                execute-keys zP
            } catch %{
                # All lines were commented, so restore the selection and uncomment them
                set-register / "\A\Q%opt{comment_line}\E\h?"
                execute-keys zs<ret>d
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by maximbaz**
This basically combines all the improvements I tried to make to the `comment-line` in one change.

---------

Fixes #2156
Fixes #2161
Closes #2160
Closes #2163

### CODE REVIEW

**Comment by maximbaz** [comment]
Oh no, it seems the `align-cursors-left` doesn't work on macOS. Does anyone have a Mac to help figure out the command that can work on both OS? Just run these two commands and see if they produce the same output, and if not, tell me which part of the pipeline fails and why:

```
❯ echo '2.5,2.9:1.3,1.11'  | tr ':' '\n' | cut -d',' -f1 | cut -d'.' -f2 | sort -n | head -n1
3

❯ echo '2.5,2.9:1.3,1.11' | sed 's/\.[0-9]\+,/.xxx,/g'                 
2.xxx,2.9:1.xxx,1.11
```

**Comment by maximbaz** [comment]
macOS issues seem to be solved, this is ready for your feedback 😉

**Comment by net** [comment]
I would rather blank lines be commented. If you don't want to comment blank lines, you can use `<a-s><a-k><ret>`; the reverse is more difficult. @shachaf

**Comment by maximbaz** [comment]
I don't mind either way, can you suggest a simple way to avoid adding trailing whitespaces? Currently the comment char is `"# "`, so by adding this to a blank like we will end up with trailing spaces.

P.S. [Should we make more things configurable](https://github.com/mawww/kakoune/pull/2184#issuecomment-402171170) instead of trying to find a solution that everyone will like?

**Comment by shachaf** [comment]
If you use `<a-s>` then the comment character will go on each line's column separately which makes the command pointless. If you want blank lines to be commented, can you describe the behavior you want? Do you want spaces inserted before the comment character, or what?

I'm fine with making things like this configurable if people can't agree on them, but Kakoune's scripting language really doesn't lend itself to it.

**Comment by shachaf** [comment]
Instead of putting `"%opt{comment_line} "` in the register, you can insert `%opt{comment_line}`, drop lines where the cursor is on \n, and then insert a space.

**Comment by maximbaz** [comment]
Just tried your suggestion, I can't get it to work on the following example:

```
1: a:
2:     b: 3
3:         c: 4
4:
5:     e: 5
```

Select lines 2-5 and execute `:comment-line`, I want to achieve the following result:

```
1: a:
2:     # b: 3
3:     #     c: 4
4:     #
5:     # e: 5
```

Without skipping empty lines we will get this result:

```
1: a:
2: #     b: 3
3: #         c: 4
4: #
5: #     e: 5
```

(This example exists also as a unit test `comment-multiple-lines-indented` by the way)

The magic is happening in `align-selections-left` command, so far it was easy - we align the selections to the leftmost cursor of the non-empty selection. But with including empty lines, the leftmost column becomes column 1. So now we need to pad the empty line with a correct amount of spaces somehow 🤔

Feels complicated, I'm happy to hear suggestions, but if you are puzzled too, I tend to keep the current logic and exclude empty lines.

**Pull request merged**
