### PR TITLE
Add CMakeLists.txt to contrib

### PR DESCRIPTION
**Pull request by tony**
Carried on from https://github.com/mawww/kakoune/pull/693#issuecomment-226737860.

Tested against e262dc1 on OS X 10.11 and FreeBSD 11-CURRENT

### CODE REVIEW

**Comment by lenormf** [comment]
This is going to need some squashing :p

**Comment by tony** [comment]
Better?

**Comment by doppioandante** [comment]
Looks good,just a small note on the msvc code path: as far as I know kakoune doesn't compile under it, but leaving it there shouldn't be a big deal.

**Comment by tony** [comment]
@doppioandante good catch, removed the mscv / conditions around that

**Comment by mawww** [comment]
Can you prepend a copyright waiver commit as well ? (see CONTRIBUTING)

**Pull request closed without merging**
