### PR TITLE
Recognize systemd timer syntax

### PR DESCRIPTION
**Pull request by maximbaz**
image

### CODE REVIEW

**Comment by Clyybber** [comment]
Unrelated, but may I ask what font you are using? I've lately seen quite a few of your screenshots and it looks beautiful.

**Comment by maximbaz** [comment]
@Clyybber it is [Fira Code](https://github.com/tonsky/FiraCode) 🙂

**Comment by lenormf** [comment]
I think it'd be better to handle all of `systemd`'s configuration files (which use the INI syntax) in a separate dedicated support script, rather than adding unrelated extensions to `ini.kak`.

Extensions used by `systemd` files are `.service`, `.mount`, `.timer`, `.target`, `.path`…

**Comment by mawww** [comment]
Yep, moving systemd file detection to an `extra/systemd.kak` file would be nice

**Pull request merged**
