### PR TITLE
Keybinding for copying selections on matching substrings vertically

### PR DESCRIPTION
**Pull request by rouanth**
A new keybinding, `^`, which allows for selecting substrings that are directly above or below the currently selected one if their contents match that of the original selection.

For example:
```rust
/// Long
/// comment
/// ...
fn main() { }
```
If the cursor is located at the beginning of the snippet, pressing `^` causes the `/` at the beginning of each of the first three lines to be selected.

### CODE REVIEW

**Comment by danr** [comment]
This is an interesting keybinding (and I now understand what you meant with it)!
It does not need to be implemented in the C++ kakoune source though, it should be possible to get it going with some scripting.

**Comment by lenormf** [comment]
As said previously, I don't think adding this to the primitives makes much sense, it sounds too specific, better keep it as a mapping in your user configuration.

**Comment by mawww** [comment]
This is an interesting binding, but I am not convinced it has wide enough applications to warrant being a built-in, I think it should be doable through a mapping.

Do you have examples of editing problems that are cumbersome to do without that binding ? It seems in many cases `C` and `<a-k>` can be used.

**Comment by rouanth** [comment]
I've provided some use cases in the issue which this request closes: https://github.com/mawww/kakoune/issues/1115. In general, I often encounter text which is distinguished by a vertical structure but isn't on a separate paragraph and doesn't have a fixed number of lines. For these cases, both `C` and `<a-k>` can be used perfectly well when editing manually; however, when doing automation with macros, `C` needs to know the number of lines, and the regular expressions required to do it with `<a-k>` in general case and without relying on its interactivity are often unnecessarily complex.

I will try to write a script that implements the keybinding, but I must warn that it can take very long for me to get to it. I guess the pull request can be rejected, but I'll leave the issue open if it's fine with you.

Thank you all for your analysis!

**Comment by alexherbo2** [comment]
https://github.com/occivink/kakoune-vertical-selection

**Pull request closed without merging**
