### PR TITLE
Remove rc/ranger

### PR DESCRIPTION
**Pull request by alexherbo2**
Rationale is `rc/ranger` is superseded by [Opening files in specific client][Open files in specific client] approach.

- https://github.com/mawww/kakoune/wiki/Open-files-in-specific-client
- https://youtu.be/v_Ffno9wiJ4

[Open files in specific client]: https://github.com/mawww/kakoune/wiki/Open-files-in-specific-client

### CODE REVIEW

**Comment by Delapouite** [comment]
I think the `terminal.kak` and `shell.kak` (more generic) must be included in `rc/extra` before deleting this script.

**Comment by alexherbo2** [comment]
I think same, but I don’t get the occasion to discuss that with @mawww.

`:shell` and `:terminal` commands are not that useful without providing the `kak` which makes use of `$KAK_{SESSION,CLIENT}` to open files.

**Comment by Delapouite** [comment]
I found that I like ranger to open with the current file selected by default

`
ranger --selectfile=$KAK_BUFFILE
`

To do so, I had to modify `shell.kak` to add : 
```
 # Ensure Kakoune sets these variables by making them appear in the source:
  # – kak_session
  # – kak_client
  # – kak_buffile
```

**Comment by alexherbo2** [comment]
I added to the wiki and my dotfiles.

**Pull request closed without merging**
