### PR TITLE
Detect filetype on buffer save too

### PR DESCRIPTION
**Pull request by Eluminae**
This allow kaking a new file, add a shebang in the first line, and get
the right filetype detected automatically on save.

### CODE REVIEW

**Comment by alexherbo2** [comment]
@Eluminae How about exposing and documenting the `file-detection` command?

**Comment by Eluminae** [comment]
I used to. But in fact, I don't think we need more than those two hooks. So I'm now not sure this is necessary.

**Comment by krobelus** [comment]
I'd love to know why Vim chooses not to do this.

**Comment by Eluminae** [comment]
Vim allow to `:e!` which will reload the file and trigger filetype detection.

**Review by Screwtapello — APPROVED** [review]

**Comment by mawww** [comment]
This is a nice change but I would like one tweak: only change the filetype of the buffer if its currently unset.

I think it would get quite frustrating if file misdetects the filetype and overwrite the user specified value at each write.

**Review by krobelus — APPROVED** [review]
> only change the filetype of the buffer if its currently unset.

I think that's already the case via `if [ -z "${kak_opt_filetype}" ]`.

(It would be nice to also get rid of the fork if the filetype is already set, but that's not a blocker)

**Comment by krobelus** [comment]
Maybe the hooks should have groups, so they can be disabled dynamically?
Something like `file-open` and `file-write`.
Some of my plain text files (where `""` is the correct filetype) are detected as ruby for some reason..

**Pull request merged**
