### PR TITLE
doc: Mention that commands requiring a client context do nothing in a draft context.

### LINKED ISSUE #2618: prompt command does nothing inside "eval -draft"
### Steps 

 1. Start a fresh Kakoune with no config:

        kak -n

 1. Type the following command:

        :eval -draft %{ prompt foo nop }<ret>

### Outcome 

Nothing happens.

### Expected 

A prompt "foo" appears, which asks for a string then ignores it.

The same command without `-draft` works fine:

    :eval %{ prompt foo nop }<ret>

### PR DESCRIPTION
**Pull request by Screwtapello**
Fixes #2618.

### CODE REVIEW

**Comment by Delapouite** [comment]
This PR needs rebasing.

**Comment by Screwtapello** [comment]
Rebased.

**Comment by mawww** [comment]
This is not quite correct, things like `on-key` do work in draft context, they are just not very useful as the key has to come in that same context.

```
eval -draft %{
    on-key %{echo -debug %val{key}}
    exec <tab>
}
```

This does write `<tab>` to the debug buffer. It is hence incorrect to says that `on-key` does nothing in draft contexts.

draft contexts do not have any clients to display things to, but they do have an input handlers, as they can handle keystrokes comming from `execute-keys`...

**Comment by Screwtapello** [comment]
I've rebased again, and made the text more accurate as @mawww described. `prompt`, `on-key` and `menu` all mention that inside a draft context, they only respond to `execute-keys` within that same context. `info` doesn't respond to input at all, so I just mentioned that it's "invisible" rather than "does nothing".

**Pull request merged**
