### PR TITLE
rc x11-repl: identify the REPL window by window id instead of title

### PR DESCRIPTION
**Pull request by listentolist**
Now it uses the window id to identify the REPL window. It is stored in the option `x11_repl_id`. That way it is possible to have different REPLs for different buffers or windows. And AFAICT there are less issues with different termcmds and shells.
#1795 #3011 #2973

### CODE REVIEW

**Comment by Screwtapello** [comment]
I think this will not be reliable - when Kakoune launches a new terminal for the REPL, that terminal will not necessarily be made the active window; lots of window managers let the user configure whether new windows should automatically be made active. Even if it is made active, it might not be made active immediately, so there's a race condition between the window-manager switching the active window, and `xdotool getactivewindow` running.

That said, there are other approaches. Many X11 terminal emulators set `$WINDOWID`, which (if present) is probably more reliable than messing with xdotool. If that's not set, a script could use the existing escape sequence to set the title to a string including the shell's pid (`$$`) then use `xdotool searchbyname` to look for it — which still depends on `searchbyname` but at least it keeps working if the window title changes later (for example, shells that put $PWD in the title).

**Comment by listentolist** [comment]
Yes, most terminal emulators set `$WINDOWID`. Then we can just change `$(xdotool getactivewindow)` to $WINDOWID`, although it doesn't work for all termcmds (e.g. gnome-terminal does not set this variable). I just changed it.

**Comment by alexherbo2** [comment]
@listentolist How to have multiple REPLs?  If you use `repl-new` two times, the second call erases the option storing the window ID of the first REPL.

How about using a `int-list` option storing the window ID of the REPLs and adding a `repl-connect` command completing the IDs to change the connection?

**Comment by listentolist** [comment]
@alexherbo2 `repl-new` opens a REPL for the current scope. So to get new REPL for the current buffer only you have to make sure that `x11_repl_id` is set in the buffer scope:
```
set-option buffer x11_repl_id ''; repl-new
```

**Pull request merged**
