### PR TITLE
rc: Deindent closing brace when after cursor (all filetypes)

### PR DESCRIPTION
**Pull request by johnisom**
Fixes issues described in #3617.

Example (▌ = cursor):

``` c
void foo(void) {▌}
/* currently on <ret> becomes: */
void foo(void) {
    ▌}
/* but with my fix becomes: */
void foo(void) {
▌}
```

### CODE REVIEW

**Comment by alexherbo2** [comment]
Will this fix apply to all filetypes?

**Comment by johnisom** [comment]
Yes, that's the indented scope of this PR.

**Comment by johnisom** [comment]
I realized my specific implementation will fail in the case of bad indentation:

``` c
  void foobar(void) {
         foobar();▌}
/* which becomes */
  void foobar(void) {
         foobar();
       ▌}
/* but should be */
  void foobar(void) {
         foobar();
  ▌}
```

This should be a fairly easy fix: I just need to make it so that when deindenting, it doesn't use `<a-lt>` but rather finds the matching brace (`m`) and indent to the same level as the line that contains the opening brace.

**Comment by johnisom** [comment]
I haven't gotten to clojure.kak or lisp.kak. Since it's been some time since I've worked with Lisp syntax, I'll probably get to them last. If anyone wants to volunteer to handle them, though please do and submit a pull request on johnisom/kakoune (on the `deindent-closing-braces` branch).

**Comment by johnisom** [comment]
Just for context and if people don't want to read the actual commits, here's the code that's being added to each file, tailored to the specific language:

``` kakrc
# ...
try %< execute-keys -draft <a-x> <a-k> ^\h*[})\]] <ret> gh / [})\]] <ret> m <a-S> 1<a-&> >
# ...
```
Let's break it apart:
| Keys | Explanation |
|---|---|
| `<a-x>` | Select whole line, placing cursor at end of line |
| `<a-k> ... <ret>` | Keep selections that match regexp (in this case, throws error if current single selection does not match, ending execution early) |
| `^\h*[})\]]` | Regex that matches the beginning of a line (`^`) followed by zero or more white spaces (tabs, spaces, etc) (`\h*`) and one of: `}`, `)`, or `]` |
| `gh` | Move cursor to beginning of line, reducing selection to size 1 |
| `/ ... <ret>` | Find and select the first occurrence of a regexp |
| `[})\]]` | Regex that matches one of: `}`, `)`, or `]` |
| `m` | Move cursor to matching brace (matching brace of `}` is `{`), extending selection to encompass whole area in-between |
| `<a-S>` | Split selection into 2 selections of length 1 at beginning and end of original selection |
| `1<a-&>` | Indent line that primary selection (closing brace) resides on to the level of indentation that the secondary selection (opening brace) resides on |

**Comment by johnisom** [comment]
Now that all filetypes have been changed, as well as some test cases added, I'm taking this out of draft (WIP) stage! There are still a few tests to be added, though no tests for these languages currently exist outside the scope of this PR:

- javascript
- awk
- cabal
- css
- cue
- dart
- d
- gluon
- java
- json
- kakrc
- latex
- nix
- perl
- php
- ragel
- python
- protobuf
- sass
- scala
- sh
- zig

This PR is now open for review and merge!

**Comment by mawww** [comment]
Wow, thanks a lot for this through PR, it reminds me that now that we have modules it might make sense to have a indentation utilities one to share the indentation logic and give them nice names, but thats a cleanup for later (assuming it proves to work well and not impact performance too much).

**Pull request merged**
