### PR TITLE
Remove "-lang" suffix from D and Go

### PR DESCRIPTION
**Pull request by casimir**
Since the language name is Go, see [golang.org](http://golang.org) for reference. This is really just a proposition for consistency.
Impacts #851.

Edit: Apply the same to D as suggested by https://github.com/mawww/kakoune/pull/848#issuecomment-252464610

### CODE REVIEW

**Comment by lenormf** [comment]
You might as well rename `dlang` to `d` as well then.

**Comment by casimir** [comment]
A quick google search for D blog post shows this is a good idea. But like I know Go Inreally don't know D. Maybe a user could validate this?

Either way I'll add a second commit for this today.

**Comment by lenormf** [comment]
I'm a dlang user.

**Comment by mawww** [comment]
I dont mind much between the two, can you get to an agreement ?

**Comment by casimir** [comment]
Since there's no ambiguity in this context I'm for the merge. It's also what you find in a lot of editors.
@lenormf any thought?

**Comment by greduan** [comment]
In this case, since there is no ambiguity in this context and I would personally guess that a filetype is named `go` not `golang`, I'm OK with this merge.

**Comment by lenormf** [comment]
Filetypes for C/C++/ObjC are c/cpp/objc, so I guess it makes sense to apply the same logic to  Go and D. I don't mind either way.

**Pull request merged**
