### PR TITLE
A 'c' column suffix selects by codepoints

### LINKED ISSUE #2724: Proposal: Select by character or display indices
Expansions such as `%val{selection_desc}` expose columns in byte index within the line, and commands such as `select` take selection in terms of byte index within line.

This makes integrations hard.  So far as I've experienced, byte-index columns aren't useful external to Kakoune.  So far, I have unicode issues with `parinfer-rust` that I will have to fix by converting coordinates to characters, and I have unicode issues with my new selection tool based on this as well.

The selection tool is written in Clojure, therefore using Java strings, so reading the file produces UTF16 characters anyway, so the byte index of UTF8 can't be used directly for converting, and if there are multiple encodings of a character in UTF8, I'll have to guess which way it occurred to interpret the bytes.

Further, converting these requires extra content from the buffer.  If I have a $kak_selection that start > column 1, I need to know the entire text of the starting line in addition to the text of the selection I probably want.  We don't have access to the text of the buffer outside of selections unless we run some keys in draft mode and save the value to an option.

So, I propose that byte indices are not exposed for scripting.  Instead, all expansions and commands use character indices.  The user can split diacritics and other compound characters, but not multibyte character encodings.

No matter how it is sliced, this would be a bit of work.  There's a couple ways to do it.  One way is to audit everything at user-interface layer (commands and expansions), and ensure they provide the right data.  Another way is to encapsulate this at the buffer layer and not expose byte indices to the rest of Kakoune.

IMHO, both add internal complexity.  Both reduce interface complexity.  The latter way contains the complexity better, but is harder.  It would be nice to figure out how to break it down into smaller steps.

(Note: It would be possible to make parallel expansions that use char indices - some already exist - and add options to commands like `select`.  I'm proposing the big change here because I think it'll be better for Kakoune.)

### PR DESCRIPTION
**Pull request by eraserhd**
Closes #2724

This only selects by codepoints right now.  If this approach is acceptable, I'll add support for a `d` suffix for display columns.

This only allows codepoint-based selection for the most recent timestamp on a buffer.  Adding support for historic timestamps will be quite tricky, but I'm willing to do it if we have a use case (or a compelling reason).

The test should be comprehensive, starting and ending on a single-byte char, a multi-byte char, selecting only a combining character, the main character plus a subset of combining characters, having a reverse selection. I was worried about failure on interesting cases - but none of them turned out to need more work, surprisingly.  I'm happy to add test cases if I missed anything.

### CODE REVIEW

**Comment by Screwtapello** [comment]
Please also document this feature in `doc/pages/commands.asciidoc` in the section for the `:select` command!

**Comment by lenormf** [comment]
Is the granularity on the feature necessary? Couldn't we pick one best-case-suits-most (codepoints for instance)?

**Comment by occivink** [comment]
@lenormf I don't know about the codepoint usecase, but it's important that `select` can be used with the format used in `$kak_selection` and similar values

**Comment by mawww** [comment]
I dont expect cases where a single `select` gets a mixed codepoint/bytes/columns coordinates, so I would encourage the use of a switch instead of suffixes for that. For the register case, we have a first elements containing some metadata (buffer, timestamp...) so we could also put something there if we wanted to support putting codepoint coordinates in a register (not convinced we have a use case for that).

I am still not really excited about such a change, as making it work with timestamps is going to be quite complex, and I expect most use cases for this comes from tools like `kak-lsp` that are running asynchronously from Kakoune (so they have not guarantee that the timestamp is still the same).

Could you elaborate on why byte offsets do not work in your case ?

**Comment by eraserhd** [comment]
I accidentally [a whole document](https://gist.github.com/eraserhd/f14469a12f379074b8ff5337cb448d34) on the two cases I have and potential solutions.

My partner suggested the possibility of another program, which I hadn't considered before and actually doesn't seem too bad, if done right.

The big reason for a change to Kakoune was about leverage: doing it in the plugins is a lot of work, and these tools are already trying to be editor-agnostic.  While I'd already started to do this for parinfer-rust, I came to the conclusion there should be an easy path to support tools which think in codepoints or display columns, rather than making column translation a concern that many plugin authors would have to deal with.

**Comment by mawww** [comment]
Thanks for that detailed document. I think making Kakoune able to communicate in terms of codepoints and columns makes sense. I still would prefer a switch provided to `select`, along with a way to get codepoints/columns based selection descs.

Regarding timestamps, it seems this would be fine in the parinfer and select-nrepl cases, as they runs synchronously. It would be an acceptable limitation for now to require it to match the current buffer state.

**Comment by eraserhd** [comment]
Cool!  This sounds like a plan.  I'll do the expansion first, since I can use it by itself.

**Pull request closed without merging**
