### PR TITLE
Change session name

### PR DESCRIPTION
**Pull request by doppioandante**
Hi, I frequently find myself wanting to give the session a more descriptive name (to ease kak -c).
This is what I came up with, any opinions?

### CODE REVIEW

**Comment by mawww** [comment]
Hello,

That wont work, we would need as well to open a new session socket and close the previous one. We need to check as well if that would impact already connected clients (I think it will not, but we need to test that).

On the feature itself, I think it makes sense to be able to change the session name after the fact, so I am in favor of adding that feature.

**Comment by doppioandante** [comment]
Hi, from my tests it seems that simply renaming the socket (link+unlink) does the trick. I don't know if this is the case everywhere, I will check tomorrow.
The connected clients don't seem to care.

I also need to check if the session name is already in use.

**Comment by doppioandante** [comment]
I couldn't find much about moving unix domain socket handles. I'm not very familiar with unix programming but from what I could understand they contain just some metadata required for the actual socket connection, so it should be OK.
I would be more confident if someone tried on cygwin or bsd though.

What name would you like for the command? It currently is :session <new_session_name>

**Comment by mawww** [comment]
renamed the command to `:namesession` to be consistent with `:nameclient` and `:namebuf` however I think we really want to changes all of these to something less ugly.

**Comment by lenormf** [comment]
Something like `:name {session,client,buffer} <str>` ?

**Pull request merged**
