### PR TITLE
New colorscheme: desertex

### PR DESCRIPTION
**Pull request by kurkale6ka**

### CODE REVIEW

**Comment by alexanderjeurissen** [comment]
Seeing as this PR introduces a new colorscheme could you provide a screenshot ?

**Comment by kurkale6ka** [comment]
screenshot_2016-12-23_11-35-00

**Comment by lenormf** [comment]
I like taking screenshots of `backtrace.cc`, it has several different atoms :)

**Comment by lenormf** [comment]
Anything pending in here?

**Pull request merged**
