### PR TITLE
add face to change whitespace colors

### PR DESCRIPTION
**Pull request by pierroelmito**
Hi,
I have made a small update in order to allow user to change white space colors. It helps increasing readibility when whitespace is displayed.
Regards,
Pierre

### CODE REVIEW

**Comment by mawww** [comment]
Hello,

Thanks for that pull request.

 Can I ask you to add a copyright waiver commit as that is your first contribution ? I think that face should be named "Whitespace" instead of "WhiteSpace", it seems to me "Whitespace" is now a full word instead of two words.

**Comment by pierroelmito** [comment]
Hi,
I have changed WhiteSpace to Whitespace and added the copyright waiver in the commit message.

**Comment by mawww** [comment]
Thanks, could you put the waiver in an empty commit, it makes it easier for me to find them when I wonder if somebody already provided one.

**Comment by mawww** [comment]
Thanks a lot, sorry for the delay in merging that.

**Pull request merged**
