### PR TITLE
Add `-group <lang>-highlight` to highlighters

### PR DESCRIPTION
**Pull request by greduan**
Earlier PR https://github.com/mawww/kakoune/pull/825

### CODE REVIEW

**Comment by greduan** [comment]
@lenormf 

> why rename the ini higlighter ?

For consistency, ironzorg saw no problem. But if it's a problem it's one revert/rebase away. :)

**Comment by greduan** [comment]
According to @mawww the `rmhl` statements also need to be put into a highlight group, I'll later add one commit adding all that stuff.

**Comment by lenormf** [comment]
You want to avoid including chunks that do nothing or that do changes unrelated to the PR. That way we avoid taking risks at introducing bugs, and keeping the changes grouped per PR.

**Comment by greduan** [comment]
@lenormf I'll move that into it's own branch when I have time. :)

**Pull request merged**
