### PR TITLE
rc lint: Fix the previous/next navigation functions, fix the diagnosis anchors, add an error message

### PR DESCRIPTION
**Pull request by lenormf**

### CODE REVIEW

**Comment by maximbaz** [comment]
I'm curious, do you actually see the lint messages now? Since big-breaking-tidy-up I see the red icon in gutter, but when my cursor is on the line, I don't see actual lint message anymore. There's nothing interesting in `*debug*` buffer, and in fact I do have the `*lint-output*` with lint messages, but they don't show up when cursor is on the line with the error.

**Comment by lenormf** [comment]
Good point, I actually don't see the message anymore either!

I'll update this PR when I've fixed it.

**Comment by lenormf** [comment]
Should be working now.

**Comment by maximbaz** [comment]
Yeah, I confirm, great job! This fixes point 5 in #2191.

**Pull request merged**
