### PR TITLE
Update the showcase videos

### PR DESCRIPTION
**Pull request by lenormf**
The new videos are wider, and show exactly what keys were hit during the demo.

You can see the changes in action [on my repository](http://lenormf.github.io/kakoune/).

### CODE REVIEW

**Comment by mawww** [comment]
The last video is missing.

**Comment by lenormf** [comment]
Actually I decided no to redo it, as it's just showing the `:new` and `:make` commands, spelled out completely on the prompt. Should I redo it ?

**Comment by alexherbo2** [comment]
I think because they are not the same size, just disable your tool to display keystrokes here.

**Comment by danr** [comment]
Now also using paragraph objects 👍 
I think the fonts and colours will have a broader appeal, too.

**Comment by lenormf** [comment]
>I think because they are not the same size, just disable your tool to display keystrokes here.

The reason is re-recorded the videos is to have the keys displayed as they're typed.

**Comment by mawww** [comment]
I'd prefer for all videos to be same size, and use the same coloscheme.

**Comment by occivink** [comment]
@lenormf 
>Also is it me or the video look a bit blurry?

vp8 is kind of a bad codec, you might get better results with vp9 which should have the same browser support.

**Comment by lenormf** [comment]
I think most browsers only support vp8 for now (if they support it at all), that's why I went for it.

**Comment by occivink** [comment]
I don't think that's correct, vp9 has been supported for a while by most browsers (with the notable exception of safari, which doesn't support vp8 anyway).

**Comment by lenormf** [comment]
According to wikipedia:

>Internet Explorer and Apple Safari are missing VP9 support completely. In March 2016 an estimated 65 to 75% of webbrowsers in use on desktop and notebook systems were able to play VP9 videos in HTML5 webpages, based on data from StatCounter.

I guess that's good enough for us? @mawww are those numbers good enough? I don't know what browser users who end up on kakoune.org use mostly, but chances are they're on firefox/chrome.

**Comment by occivink** [comment]
It's probably safe to ignore IE users, but there is a sizable osx userbase (#973) so ideally we should also have h264 versions of these videos. But my point is that vp8 is not going to have any more support than vp9.

**Comment by lenormf** [comment]
I already have the x264 encoded videos (I just transcoded them into vp8 after recording them), I think I'll put them as alternative for the vp9 encoded clips. I might also add a couple other examples of basic things to do with the editor, so I promoted this PR to WIP, in the meantime,

**Comment by lenormf** [comment]
I decided not to re-encode in vp9, as the only difference I saw on the videos was the size (⅓ bigger vp9 clips). The blurry effect I'm seeing comes from my browser, which is resizing the videos for no reason. Internet Explorer and Safari users will now be able to watch the clips, I've added the original mp4 recordings to the page.

I also added a new demo showing off how to wrap arbitrary lines in a document.

**Comment by mawww** [comment]
Any chance to get the multi client video redone as well ? I'd really prefer if all videos were the same size, using the same colorschemes.

**Comment by lenormf** [comment]
It will be done, yes.

**Comment by lenormf** [comment]
I updated the last video on the list, I won't modify this branch anymore unless somebody has a suggestion.

**Pull request merged**
