### PR TITLE
Add reStructuredText highlighting

### PR DESCRIPTION
**Pull request by Geemili**
This pull request will solve #1650 by adding highlighting support for reStructuredText. Or, it will. Features highlighted so far:

- [x] Headers
- [x] Bold
- [x] Italic
- [x] `.. code::` directives
- [x] Inline literals

Some features that would be good to add:

- [ ] Links
- [ ] Bullet lists
- [ ] Enumerated lists
- [ ] Definition lists
- [ ] Literal blocks
- [ ] Line blocks
- [ ] Block quotes
- [ ] Transitions

### CODE REVIEW

**Comment by lenormf** [comment]
Do your regex to highlight bold/italic tokens work properly? If yes, would you mind backporting them to the Markdown highlighter? Currently `**text**` is highlighted as being both bold and italic.

**Comment by Geemili** [comment]
@lenormf Good idea! I made a separate pull request for it; #1759

**Comment by mawww** [comment]
Can you clean up the commits, squash them in a single 'Add reStructuredText support script', along with the copyright waiver commit as a second one.

**Comment by Geemili** [comment]
@mawww 
Okay. The commits should be cleaned up.

**Pull request merged**
