### PR TITLE
Docs: add missing [<switches>] in commands signatures

### PR DESCRIPTION
**Pull request by Delapouite**

### CODE REVIEW

**Comment by Screwtapello** [comment]
What's the difference between `[<flags>]` and `[<switches>]`?

We might as well make the documentation match the terminology used in the code.

**Comment by mawww** [comment]
Yeah, we should choose one and use only that. Also, various commands actually support flags/switches in many positions, not only after the command name itself. Thats generally the rule, and only certain commands will only allow switches at start.

**Comment by lenormf** [comment]
I always thought flags were switches that didn't take any argument.

**Comment by Delapouite** [comment]
All `<flags>` have now been renamed to `<switches>` since it was both used in infoboxes and in the code itself.

**Pull request merged**
