### PR TITLE
Makefile: use PKG_CONFIG, not pkg-config

### PR DESCRIPTION
**Pull request by somasis**
As to follow one of the nice autotools standards.

### CODE REVIEW

**Comment by lenormf** [comment]
Since the project doesn't use the `autotools` at all, why follow this particular convention? As far as I know, this variable won't be used on any of the systems that have `pkg-config`, so it doesn't help much.

**Comment by somasis** [comment]
Because it very well could be used. PKG_CONFIG is something that often 
gets set when cross-compiling.

**Comment by lenormf** [comment]
That's very weird, we don't even support GNU targets in the `Makefile`, but we now have one variable used by a build system that's not being used to build the project?

**Comment by mawww** [comment]
That fixes a problem I experienced while updating my build script for kakoune on exherbo, using plain pkg-config fails because its usually wrong when cross compiling, respecting an eventual PKG_CONFIG env var fixes it.

**Comment by mawww** [comment]
We do respect `CXX` to set the C++ compiler, so I think we have `prior art` already, `PKG_CONFIG` is part of the build system tools we now rely on.

**Pull request merged**
