### PR TITLE
rc spell: Re-implement message processing in Awk

### LINKED ISSUE #3399: spell check: delays with tex files.
### Steps 

open a `tex` file with a few hundred lines.

Invoke `spell en` 

### Outcome 

Nothing happens or There's usually an enormous delay which can last up to a minute and a half before it kicks in.

On longer lines this behavior worsens. 

### Expected 
 
To highlight spelling errors as expected within a reasonable timeframe.

Tested with v2020.01.16 and also with https://github.com/mawww/kakoune/commit/6766297623e9718db5b2b09bd655fe183acdcf67

### PR DESCRIPTION
**Pull request by lenormf**
Plain shell takes too long on large files.

Fixes #3399

### CODE REVIEW

**Comment by lenormf** [comment]
As mentioned in #3399, spell-checking [this 44kB file](http://mirrors.ctan.org/macros/plain/base/plain.tex) takes ~25s on my computer with the current implementation, and ~3s with this PR.

**Comment by Delapouite** [comment]
Oh! The difference is really significant. I had not idea of such a perf gap between shell and awk. Thanks for investigating this lenormf.

**Comment by codesoap** [comment]
The spell command is now broken on OpenBSD. The problem seems to be the `/* */` style comments. (POSIX)[https://pubs.opengroup.org/onlinepubs/009695399/utilities/awk.html] says the following about comments:

> A comment shall consist of any characters beginning with the number sign character and terminated by, but excluding the next occurrence of, a \<newline\>.

Changing the two comments to that style seems to fix it for the OpenBSD awk and also works with GNU awk.

Should I make a new PR, or can this be fixed on this PR (honest question; I don't know how GitHub works here)?

**Comment by lenormf** [comment]
Please make a new PR, this one was merged and Github considers it closed.

**Pull request merged**
