### PR TITLE
Add editorconfig script

### PR DESCRIPTION
**Pull request by doppioandante**
[link to the gist](https://gist.githubusercontent.com/doppioandante/daaccd116834c3900024/raw/66854d529958fa2b47f7e5aeb5758b059537e28d/editorconfig.kak)

### CODE REVIEW

**Comment by lenormf** [comment]
It would be more convenient to have an actual implementation in the PR rather than a link to a function, simply pulling a branch is more convenient than downloading/creating a file locally.

Other than that, it might not be a good idea to completely wrap the code logic into `awk` just yet, at least not until we can have custom interpreters (in which case you would be able to just use %awk{}).

**Comment by doppioandante** [comment]
@lenormf what's the alternative? I did like that because I've seen it in a script somewhere (maybe it was clang.kak?)

**Comment by lenormf** [comment]
The alternative is to use mainly the language that is being interpreted, as opposed to wrapping the entire function in a program which uses the current interpreter as a process launcher.

The `clang.kak` script uses `awk` because it would be complicated to have the same equivalent code written in pure bash. On the other hand a few `if/else if` statements with a few regular expressions should be fairly simple to have done in shell script.

**Comment by doppioandante** [comment]
I see, thank you very much for the input, I will see what I come up with.

**Comment by mawww** [comment]
I dont really mind this is a full awk script, the argument against direct custom interpreter is that its really easy just to do `%sh{ myinterpretter "..." }` so I wont complain if a script uses that.

So, as you prefer, I can merge that version, or if you want to change it to use sh directly, you can as well, I wont merge it if you use non posix features in sh however.

Also, BOM option syntax changed, its `none` and `utf8` now instead of `no` and `utf-8`

**Comment by mawww** [comment]
Hi, would you mind changing that pull request so that the script gets included in Kakoune ? out of the box editorconfig support would be nice.

**Comment by doppioandante** [comment]
As soon as I have time I will!

**Comment by lenormf** [comment]
Whenever you do though, remember to modify the values assigned to the variables whose type changed some time ago (i.e. `BOM` is a flag now).

**Comment by rennis250** [comment]
Is there any reason to not include this now?

**Comment by doppioandante** [comment]
Sorry I forgot to mention that I updated it.
Also, it sets the indentation options to the buffer level, is this a good idea?

**Comment by FranzSkuffka** [comment]
How do I use this?

**Comment by mawww** [comment]
You can put the following line in you kakrc:

```
hook global BufOpen .* %{editorconfig-load}
```

That will set options from editor config for every file you open in Kakoune.

**Comment by FranzSkuffka** [comment]
I have trouble getting this to work - I'm on OSX 10.12.5.
The command does execute, I have tested this. But the editorconfig is not applied.

**Comment by lenormf** [comment]
@FranzSkuffka create a new issue if you have trouble using a module, otherwise this comment will most likely be forgotten as it's made on a closed PR.

**Comment by alyssais** [comment]
For @FranzSkuffka and anybody else stumbling across this thread because editorconfig doesn't seem to be working, you need to install [editorconfig-core-c](https://github.com/editorconfig/editorconfig-core-c), eg with `brew install editorconfig`.

**Pull request closed without merging**
