### PR TITLE
Add syntax highlighting for Nix package manager

### PR DESCRIPTION
**Pull request by MarSoft**
Based on PHP highlighter. It is not ideal yet but much better than nothing.

### CODE REVIEW

**Comment by Delapouite** [comment]
Great! Could you squash your commits into one please? Thanks.

**Comment by MarSoft** [comment]
Done.

**Comment by mawww** [comment]
Hello,

I dont think I have a copyright waiver commit from you in the git log, could you add such a commit ? (see the CONTRIBUTING file).

Cheers.

**Comment by MarSoft** [comment]
Done, thanks @mawww!

**Comment by MarSoft** [comment]
Bump. Can this be merged, or is there anything left to do beforehand?

**Comment by mawww** [comment]
Sorry for the delay in merging that. Thanks !

**Pull request merged**
