### PR TITLE
Logo proposal.

### PR DESCRIPTION
**Pull request by p0nce**
This is in reply to #249, it happens I fancy doing logos :)

### CODE REVIEW

**Comment by mawww** [comment]
Looks nice, it seems inspired by the Vim logo, was that an influence ?

**Comment by p0nce** [comment]
Absolutely, also I saw that neovim also got inspired by the V of vim.

**Comment by mawww** [comment]
Could you make those tweaks: merge the two branch of the V, and tweak the background diamond so that the light appears to come from a specific direction ?

Not sure if that would look better, but I'd like to take a look.

**Comment by p0nce** [comment]
Why not, give me some days.

**Comment by p0nce** [comment]
Made some updates.

**Comment by mawww** [comment]
Looks nice ! could you merge that commits in a single one and add a copyright disclaimer one before (see the CONTRIBUTING file)

**Comment by p0nce** [comment]
Squashed and rebased (Gaaah `git rebase` has eaten my empty commit 3 times, very annoying)

**Pull request merged**
