### PR TITLE
Add window_{top,left,range_column,range_line} vars

### PR DESCRIPTION
**Pull request by Delapouite**
Hello

This PR is an attempt at solving https://github.com/mawww/kakoune/issues/675

The naming of `window_range_*` is not that great, but it follows the internals.

Also while displaying the value of `window_left` in my status line, I found this value to be a bit *flacky* moving from `0` to `1` randomly with no apparent reason.

### CODE REVIEW

**Comment by danr** [comment]
You can calculate `window_top` this way: 

```
decl int window_top
def update_window_top %{
    eval -save-regs ct %{
        eval -draft -no-hooks %{
            reg c %val{cursor_line}
            exec gt
            reg t %val{cursor_line}
        }
        set window window_top %sh{ echo $(($kak_reg_c - $kak_reg_t)) }
    }
}
```

By pressing `gb` instead you could get the bottom line of the window.

Note that we have the `window_height` value availabe too.

I don't know of any way of getting the left and right columns since there are no corresponding goto commands.

**Comment by Delapouite** [comment]
Thanks! Yes you're right about `window_top`.
The initial demand was more about exposing the `window_range_*` ones, but after looking at the code, it felt no harm to also exposed the other two so it can avoid this `eval -draft exec` dance.

**Comment by lenormf** [comment]
It's simpler to expose variables manage by the editor directly, to handle updates due to e.g. terminal resizing.

Note that the above snippet won't work properly as `gt` will take `scrolloff` into account, making the window offset incorrect if context lines are displayed above the selection upon hitting `gt`.

My original issue mentioned the offset of the code-rendering area and its length to be able to know where on the terminal it is located, which boils down to the current part of the buffer that is show minus the statusbar (and other widgets displayed), as well as any highlighter added to the current window.

**Comment by danr** [comment]
The snippet works with `scrolloff`, it simply looks at the cursor line.

**Comment by lenormf** [comment]
If `window_top` is supposed to be how far away the top-most line currently displayed is from the first line, then `cursor_line` will be off by as many lines are set in `scrolloff`.

If it's supposed to be the offset on the terminal of the buffer rendering area compared to the top-most border of the terminal, then it's incorrect.

**Comment by mawww** [comment]
I think it makes sense to expose that data, but I am not really keen on adding 4 new env vars just for that. I am wondering if it would be better to expose the window range as a single var, something close to the selection syntax (say `<pos line>.<pos column>,<height>.<width>`). Not sure if thats really better as it makes accessing the data a bit more painful (as you now need to go through `cut` or similar to get the data).

Yet another good reason to find a way to expose structured data more nicely to the shell...

**Comment by Delapouite** [comment]
Closing because `window.range()` was removed in https://github.com/mawww/kakoune/commit/0bdde

**Pull request closed without merging**
