### PR TITLE
Don't bother wrapping before word if it's longer than a full line anyway

### LINKED ISSUE #2245: Wrapped indented line is pushed down
### Steps

`kak -n`

Type this, indented with two spaces:

```
  short line

  loooooooooooooooooooooooooooooooooooooooooooooong line
```

Enable wrapping: `:addhl global/ wrap -word -indent`

### Outcome

Notice that the line is pushed down:

kak-line-push

As a user I don't see any reason why it shouldn't stay on the line above:

image

### Expected

The line is not pushed down in this case.

### PR DESCRIPTION
**Pull request by GrantMoyer**
Fixes #2245.

Doesn't bother wrapping before a word if it is longer than a full line and would be broken in the word anyway. Instead just break inside the long word on the first line.

### CODE REVIEW

**Comment by maximbaz** [comment]
Oh thank you soooo much for this! Works well :)

**Comment by GrantMoyer** [comment]
Squashed commits as in #2811

**Comment by mawww** [comment]
Hi, just to let you know, I think this is a good change, but I need to take the time to review it. It looks a bit bigger than I would have expected, so I need to take the time to see if there is no way around adding that much code to fix this issue (if you come up with a smaller, cleaner change in the mean time, I'll be extra happy).

**Comment by GrantMoyer** [comment]
I figured something like that was the case, since changing C++ code is potentially a lot more dangerous than changing kakscript, escpecially when it comes to unicode.

The reason for the size of the change is basically that the current loop only iterates until the end of the current line. The new loop need to iterate past the end of the current line to see if the last word is longer than a whole line. It's possible these loops could be combined, but then we'd need to track whether or not we'd already reached of full line length within the combined loop. I'm not sure if this would lead to a smaller change overall.

**Comment by mawww** [comment]
Hello,

Thanks for this PR, I gave a quick shot at implementing this myself initially to understand your own implementation, but I believe I arrived to a simpler change. I might have overlooked some corner case so please tell me if the pushed version has some drawbacks. Thanks again for proposing this change and for the initial implementation.

Cheers,

Maxime.

**Comment by mawww** [comment]
Ahh, just understood the corner case that required you to pass the line length parameter. I'll add a few test cases and fix that.

**Comment by GrantMoyer** [comment]
Your implementation looks correct to me.

**Pull request closed without merging**
