### PR TITLE
write: do not overwrite existing file

### PR DESCRIPTION
**Pull request by voroskoi**
Do not let Kakoune to overwrite existing files with the buffer content without using w! or write! if the argument does not match the buffer name.
Writing without arguments works as before.

Fixes: #3587 #3717

- [x] Code changes
- [x] Make failing tests work again
- [x] Add tests for this change

### CODE REVIEW

**Comment by lenormf** [comment]
The random side effect is not appealing, this is better handled with a custom command.

**Comment by voroskoi** [comment]
Given the fact that `e` and `w` are next to each other at least on a QWERTY/QWERTZ keyboard this behavior is desired even in `kak -n` mode.
There are already two bug reports, a [forum thread](https://discuss.kakoune.com/t/prevent-write-to-overrite-existing-file-by-default/992) based on this issue and nvi/vim/neovim works this way too.

The tests (3 failing for me) has to be fixed, maybe there are plugins out there need a `s/write/write!/`, but I still think it is the right way.

- [ ] Make failing tests work again.

**Comment by lenormf** [comment]
My reservation about this change is that the side effect is unpredictable unless you know about/experience it beforehand. The primitive is called `write`, and that's what the editor should do (or attempt to, c.f. filesystem permission errors) when you use it.

It's also more elegant than inverting the paradigm and delegating actual writing to `write!`.

Look at how `edit -existing` does it: the side effect is opt-in, and expected.

I also have fat finger issues, that's why I have the following (somewhat related) instruction in my configuration:

```kak
unalias global wq write-quit
```

**Comment by voroskoi** [comment]
First of all, thank You for your valuable feedback, I appreciate.

I do understand your concern, but `edit` and `write` is two different things:
 - Using `edit -existing` will guarantee that you do not create a new file, so the default behavior do not make any harm to the user, worst case he/she ends up with an empty buffer.
 - OTOH `write existing.file` by default overwrites someone previous work on a file, which can be really annoying.

If you look at `edit` it will not reopen an existing file if it has a modified version in the buffer, even if reverting the reload is just pressing `u` once. So `edit` is safety first by default.

My the main point would be making write a bit safer. I can change the patch to add `-existing` option to `write` but I would like to **change default action**, adding `-existing` would allow *overwriting* without using `write!`. Does it sound acceptable for You?

I would like to also note that this would only change the behavior if you want to use `write some.file` (this is "save as" in GUI apps) with an existing file **and** that is not the one open in the buffer. So severity is much lower, you do not have to use `write!` all the time as you implied. I would not call it inverting the paradigm.

You are absolutely right, this could be handled in `kakrc` too (as seen in the linked forum thread), but as I said before, I think we should change the default behavior.

**Comment by voroskoi** [comment]
I do not think it will be merged.

**Pull request closed without merging**
