### PR TITLE
Add Red Phoenix colorscheme

### PR DESCRIPTION
**Pull request by boj**
Dark terminal colorscheme based on dkeg's work located on https://terminal.sexy

2018-07-02-140149_1345x1079_scrot

### CODE REVIEW

**Comment by net** [comment]
That looks great. The highlight contrast seems poor though.

**Comment by mawww** [comment]
I agree that the selection with red text seems a bit hard to read, I dont mind that much but if you wish to tweak it please do.

**Comment by boj** [comment]
No problem, I'll experiment a little further and push a change with better contrast.

**Comment by boj** [comment]
2018-07-04-131433_923x449_scrot

That seems to be a tad better.

**Comment by lenormf** [comment]
Also split those selections, so we can see how secondary selections are highlighted!

**Comment by mawww** [comment]
Seems the `face` commands in this colorscheme are using the old, unscoped syntax, you are probably using a pretty old version of Kakoune, faces can now be set to different values in different scopes (global/buffer/window). the `face` command now takes a scope arguments as first argument.

**Comment by boj** [comment]
I've updated this to use the modern syntax.

**Pull request merged**
