### PR TITLE
Update README.asciidoc with debian installation instructions.

### PR DESCRIPTION
**Pull request by matthewjberger**

### CODE REVIEW

**Comment by lenormf** [comment]
This section is more of a list of the different packages that exist for kakoune in several distributions, and adding commands that are generic across all UNIX systems doesn't make much sense (the dependency installation phase, followed by `git clone … && cd src && make install`).

However, there is a script ([`contrib/make_deb.bash`](https://github.com/matthewjberger/kakoune/blob/master/contrib/make_deb.bash)) that generates a .deb package for debian-based systems that users of those systems might miss, so I think it'd be more relevant to describe quickly how to use it as a tip. If an official package ever makes his way to the upstream repositories, we'll update that section with its name (`sudo aptitude install kakoune` or something).

**Comment by matthewjberger** [comment]
Would something like this be more appropriate? I wasn't aware of this script until I read your comment, and the script worked properly for me when I ran it with the appropriate flags set.

**Comment by lenormf** [comment]
Yea I think that's more relevant, thanks.

**Comment by mawww** [comment]
Hi, Can you use your name for the copyright waiver commit ? and maybe squash the various changes together in a single commit ?

**Comment by matthewjberger** [comment]
I cleaned up the commits as you requested. Thank you for your consideration!

**Comment by mawww** [comment]
Thank you !

**Pull request merged**
