### PR TITLE
POSIX changes

### PR DESCRIPTION
**Pull request by lenormf**
A work in progress branch that aims at making shell scripts POSIX-compliant.

Some references:
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html
http://www.etalabs.net/sh_tricks.html

### CODE REVIEW

**Comment by rennis250** [comment]
This raises a recent question that I have had. Is the "-r" option of sed a POSIX standard? This option is depended upon in a number of kak scripts. However, the default sed binary on OS X does not recognize that option and fails.

**Comment by mawww** [comment]
According to http://pubs.opengroup.org/onlinepubs/9699919799/utilities/sed.html sed does not support the -r option, so we should get rid of that.

**Comment by lenormf** [comment]
Yes, raw strings that don't contain any backslash or flags should be fine to use with `echo`, I just replaced them all out of lazyness.

**Comment by lenormf** [comment]
@rennis250 GNU tools don't fare well with their BSD equivalents, in some cases. Speaking about `sed` specifically, I think we should be able to use kak instead, that way the scripts would be compatible.

**Comment by mawww** [comment]
Whats the status of this PR ?

**Comment by lenormf** [comment]
Still wondering whether it's good to replace all calls to `echo` with `printf %s\\n`, or actually think about what's passed to `echo` and leave it be. I replaced everything in the original commits, but maybe I've traded readbility for consistency where it could have been avoided.

I'm going to rebase this whole thing against master and remove the `WIP` tag in the title once it's ready to be merged.

**Comment by mawww** [comment]
I'd be in favor of keeping echo fo clearly valid cases.

**Comment by lenormf** [comment]
OK I think that will be all for this PR, I've rebased on master and I'm ready to squash all the commits.

Fun fact: for my tests I changed the default shell invoked by kak with `posh` (https://packages.debian.org/sid/posh), which helped me find a mistake in the `colorscheme` function. Maybe there should be an option that holds the path to the shell that would execute shell scripts, so that we don't need to recompile to check that scripts are POSIX-compliant ?

**Pull request merged**
