### PR TITLE
Use shifted key codes on kitty (ready)

### LINKED ISSUE #4242: mapping percent w/ kitty
I used to use a mapping which used `<a-percent>` (something like `kakoune.cr`'s `map -docstring 'select all occurrences of current selection' global normal <a-percent> ':select-highlights<ret>'`)

It used to work in the past but since one of the last updates of either kakoune (building from HEAD) or kitty it doesn't do anything anymore.

I'm on
kitty 0.21.1
kakoune 8fdda6d
macOS 11.4

`:buffer *debug*; set -add window debug keys<ret>` reports:
```
Client 'client0' got key '<a-s-5>'
```

changing the shortcut to `<a-s-5>` throws this error on startup:
```
Shift modifier only works on special keys and lowercase ASCII, not '5'
```

`kitty @kitten show_key` reports:
```
UNIX        send_text
%        %
^[%        \x1b%
```

### LINKED ISSUE #4333: Forward jump no longer working in kitty (regression)
### Steps 
- Open a scratch buffer
- Jump to end of buffer (`ge`)
- Jump back (`<c-o>`)
- Attempt to jump forward again (`<c-i>`)

### Outcome 
Nothing happens.

### Expected 
The selection should jump back to the end of the buffer.

### Comments
This appears to be a regression that was introduced somewhere between v2020.09.01 and v2021.08.28.

### PR DESCRIPTION
**Pull request by eraserhd**
Adjusts #4159.
Closes #4242.
Closes #4333.

## How this works

This implements Kitty's [keyboard progressive enhancement](https://sw.kovidgoyal.net/kitty/keyboard-protocol/).  Basically, after enabling the CSI u mode, Kitty's progressive enhancement code is sent, which should be ignored by other terminals.

The progressive enhancement protocol uses "sub-arguments" separated by colons, so that instead of sending just the codepoint of the key pressed, it will also send the shifted key code and the layout key code.  We only use the shifted key code.

This means that we now have enough information to make, say `<a-(>` as the key, instead of `<a-s-9>`.  Without progressive enhancement, we can't do that unless we know the user's physical keyboard layout (or worse, assume it is ANSI).  In this PR, when a shifted character is given, we always use it and remove the shift modifier.

The previous work-around for alphabetic characters is removed, since this one works more generally.

## Testing

* In kitty, `<a-(>`, `<a-)>`, `<a-%>` etc. now work
* In kitty, `J` `K` etc. still work as they should and aren't reported as `<s-j>`, `<s-k>`.
* In kitty, `<s-pageup>` and `<s-pagedown>` are reported as they should, because those keys do not have shifted variants.
* In tmux, all the above still works.  (I assume tmux doesn't support CSI u, right?)

## Refactoring

I started refactoring the CSI key parsing code, but the refactor ended up big and I'm not so certain @mawww will like, so I'll make that a separate PR.

### CODE REVIEW

**Comment by jtrees** [comment]
You. Are. Da. Man. Seriously, this will boost my productivity immensely. Thanks so much!

P.S.: It works. :) I didn't test every possible key combination but the ones that matter to me look good.

**Comment by eraserhd** [comment]
Tested under tmux (as a non-xterm-like terminal) and kitty and Terminal.app, and `<a-)>` works on all three.

Started to refactor key parsing - extracting a CSIKey class and breaking up the large `parse_csi` function.  A little bit more to go yet.

**Comment by raiguard** [comment]
I too can confirm that this has fixed the problem! Thank you @eraserhd :heart:

**Comment by jtrees** [comment]
I just found a key combo that still doesn't seem to work with this PR: <c-i>

Can anyone confirm?

**Comment by eraserhd** [comment]
> I just found a key combo that still doesn't seem to work with this PR:

The key combo was eaten by GitHub's markdown processing.  Can you paste it in backticks or use HTML entities?

**Comment by jtrees** [comment]
Oops, sorry. I updated the comment.

**Pull request merged**
