### PR TITLE
Add handlebars syntax highlighters

### PR DESCRIPTION
**Pull request by haarts**
Please review this with some care as I'm very new to Kakoune.

### CODE REVIEW

**Comment by lenormf** [comment]
Could you squash all the commits please?

**Comment by haarts** [comment]
Funny you would ask that. I just spent some time making pretty commit out of the one large one I had. :)

**Comment by lenormf** [comment]
It's a good practice generally, but since it's only a single file with not many changes we don't need to add much more than one commit upstream.

**Comment by mawww** [comment]
Hello,

Can you add a copyright waiver commit as well ? See the CONTRIBUTING file.

Cheers.

**Comment by haarts** [comment]
@mawww Done!

**Pull request merged**
