### PR TITLE
Add basic PHP syntax highlighting

### PR DESCRIPTION
**Pull request by leemachin**
Shamelessly adapted from the highlighting for javascript :) it's fairly naïve but looks okay to me.

captura de pantalla 2016-12-16 a las 19 33 03

### CODE REVIEW

**Comment by doppioandante** [comment]
Thanks I was really missing this but I never had time to do it, I will try it for a bit and see how it works.

**Comment by mawww** [comment]
Thanks

**Comment by haarts** [comment]
I know this PR is closed but I have a question for @leemachin nonetheless: could you describe how you created the highlighter? I'm currently looking into creating one for Handlebar files but I'm unsure how to approach this best. Thanks in advance!

**Comment by leemachin** [comment]
@haarts I copied the highlighter for javascript, changed all the instances of 'javascript' to 'php', then updated the regexes to match the keywords that PHP uses (and to recognise types/classes).

For handlebars a good point of reference might be the highlighters for pug, haml, or html. Multiple languages in one buffer are supported, which makes me think that you could enable html highlighting first and then use a handlebars highlighter for the rest. But I couldn't offer anything more specific than that, sorry.

**Comment by haarts** [comment]
But how did you test your PHP highlighter? Is there a way to reload the syntax file or something?

**Comment by leemachin** [comment]
@haarts I added it to my scripts directory, opened a PHP file in a new editor, and checked that the syntax was coloured (when previously it was completely unhighlighted). No automation for that :)

**Comment by haarts** [comment]
Just some manual reloading then! Thanks.

**Pull request merged**
