### PR TITLE
Use c-family's next line indentation for Java files

### PR DESCRIPTION
**Pull request by dermesser**
Make editing Java less annoying with this simple change!

### CODE REVIEW

**Comment by lenormf** [comment]
I don't think partly handling java buffers in the `c-family` script is a good solution, you'll have to find a way to keep hooks where they belong (i.e. modify the java file).

**Comment by mawww** [comment]
Hello,

We have different options here:

* We add java indentation directly to c-family.kak, as you proposed, which is not very satisfying because we have java support in both c-family.kak and java.kak.
* We copy the indentation code from c-family.kak to java.kak, which duplicates code, but allow us to fix some incompatibilities (we dont want to add a semicolon after class closing brace in java).
* We reference the `_c-family-indent-*` commands from java.kak, in the existing filetype detection hook, which adds a dependency between java.kak and c-family.kak

None is totallly ideal, I guess the simple change you propose could be merged and we could eventually fix that more cleanly later.

Any additional feedback ?

**Comment by lenormf** [comment]
I'd rather go for #3, creating a dependency seems more sane than sprinkling keywords in an unrelated file.

**Comment by alpha123** [comment]
+1 to @lenormf, a dependency with c-family seems reasonable since Java is, after all, a C-syntax language.

**Comment by mawww** [comment]
Ok, option 3 seems fine, can you change the pull request to implement that ?

**Comment by mawww** [comment]
This is pretty out of date, closing.

**Pull request closed without merging**
