### PR TITLE
rc: Fix calls to `mktemp`

### PR DESCRIPTION
**Pull request by lenormf**
Allow `mktemp` to make use of the `TMPDIR` environment variable when
calling it with a template.

Don't use the deprecated `-t` flag.

### CODE REVIEW

**Comment by casimir** [comment]
This PR break all the modified scripts on macOS.

Example for lint.kak:
```
*** This is the debug buffer, where debug info will be written ***
shell stderr: <<<
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
mkfifo: /fifo: Permission denied
>>>
Error: 1:1: 'lint' 1:1: 'eval' 1:1: 'write' /buf: Permission denied
```

**Comment by lenormf** [comment]
So the mac implementation excepts a `-t` flag to know what format to use, but the GNU implementation considers this flag deprecated (and will potentially remove it in newer releases) and doesn't seem to take `$TMPDIR` into account all the time unless the mac-unsupported `-p` flag is passed…

**Comment by mawww** [comment]
Can we just use `mktemp -d ${TMPDIR:-/tmp}/blah-XXXX` in that case ? or will that break on OSX ?

**Comment by lenormf** [comment]
I think this will work, I'll adapt my changes.

**Comment by casimir** [comment]
It's working with just `-d` on OSX.

**Comment by lenormf** [comment]
It doesn't on all versions, i.e. on OS X 10.10.5.

**Comment by mawww** [comment]
Whats the problem there ?

**Comment by lenormf** [comment]
It simply shows a usage message [apparently](https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x#comment522946_84980), the template was probably made optional in recent versions.

**Comment by lenormf** [comment]
Follow up in #1449.

**Pull request merged**
