### PR TITLE
Add the duck assistant discussed on the discourse

### PR DESCRIPTION
**Pull request by CharlesGueunet**
Add the duck assistant discussed [here](https://discuss.kakoune.com/t/future-assistants/66/3)

result:

duck

Best,
C.

### CODE REVIEW

**Comment by purxiz** [comment]
I'm not sure if this is the right place for this dicussion, but would it make more sense to be able to set the assistants dynamically? I.e. in kakrc somehow?

**Comment by CharlesGueunet** [comment]
I agree with the idea.  
Two remarks:
* I think this would requires its own MR
* I think some assistants should still be available in the source code for performance reasons.

**Review by somasis — CHANGES_REQUESTED** [review]
`doc/pages/options.asciidoc` ought to have this assistant added to the list in this commit as well.

**Comment by CharlesGueunet** [comment]
@somasis you are right, done

**Comment by CharlesGueunet** [comment]
@mawww if you have the time for a quick review :) this work should be ready

**Comment by lenormf** [comment]
From what I can tell, this assistant comes from [this page](https://www.asciiart.eu/animals/birds-water), and the site [requires attribution](https://web.archive.org/web/20181216203205/http://asciiartist.com/wp/respect-ascii-artists-campaign) if any ASCII art is to be used.

That means the PR cannot be merged into an UNLICENSE’d project, unless you draw the assistant yourself and place it under the UNLICENSE yourself. But then having [more than three assistants is considered overkill](https://github.com/mawww/kakoune/issues/1753#issuecomment-350225838).

**Comment by CharlesGueunet** [comment]
@lenormf you are completely right about the origin of this art, I found it on the discourse and did not look further. I close the PR as the licenses are not compatible.

**Pull request closed without merging**
