### PR TITLE
Fixes #1051. Added string length check when checking switch params

### LINKED ISSUE #1051: Crash with :echo -debug %opt{ui_options}
It seems that passing an empty option to `echo` with either the `-debug` or `-markup` flag will crash Kakoune.

Example:

```
echo -debug %opt{ui_options}
```

Backtrace:

```
uncaught exception (N7Kakoune13assert_failedE):
assert failed "from >= 0 and from <= str_len" at ./string.hh:261
[Debug Infos]
pid: 15975
callstack:
0   kak                                 0x000000010c866b37 _ZN7Kakoune9BacktraceC1Ev + 29
1   kak                                 0x000000010c8667d6 _ZN7Kakoune16on_assert_failedEPKc + 46
2   kak                                 0x000000010c8aafd8 _ZNK7Kakoune9StringOpsINS_6StringEcE6substrENS_9ByteCountES3_ + 72
3   kak                                 0x000000010c935994 _ZN7Kakoune16ParametersParserC2ENS_9ArrayViewIKNS_6StringEEERKNS_13ParameterDescE + 274
4   kak                                 0x000000010c878fbf _ZNK7Kakoune14CommandManager22execute_single_commandENS_9ArrayViewIKNS_6StringEEERNS_7ContextERKNS_12ShellContextENS_12DisplayCoordE + 113
5   kak                                 0x000000010c8795fb _ZN7Kakoune14CommandManager7executeENS_10StringViewERNS_7ContextERKNS_12ShellContextE + 815
6   kak                                 0x000000010c932d81 _ZNSt3__110__function6__funcIZN7Kakoune7commandERNS2_7ContextENS2_12NormalParamsEE3$_2NS_9allocatorIS6_EEFvNS2_10StringViewENS2_11PromptEventES4_EEclEOS9_OSA_S4_ + 975
7   kak                                 0x000000010c8d8734 _ZNKSt3__18functionIFvN7Kakoune10StringViewENS1_11PromptEventERNS1_7ContextEEEclES2_S3_S5_ + 44
8   kak                                 0x000000010c8d6f4e _ZN7Kakoune10InputModes6Prompt6on_keyENS_3KeyE + 1300
9   kak                                 0x000000010c8d059e _ZN7Kakoune9InputMode10handle_keyENS_3KeyE + 30
10  kak                                 0x000000010c8d0d52 _ZN7Kakoune12InputHandler10handle_keyENS_3KeyE + 172
11  kak                                 0x000000010c8723bf _ZN7Kakoune6Client22process_pending_inputsEv + 653
12  kak                                 0x000000010c875d47 _ZNK7Kakoune13ClientManager22process_pending_inputsEv + 29
13  kak                                 0x000000010c8f96d6 _Z10run_serverN7Kakoune10StringViewES0_NS_11BufferCoordEbbb6UITypeNS_9ArrayViewIKS0_EE + 2123
14  kak                                 0x000000010c8fc4f5 main + 5883
15  libdyld.dylib                       0x00007fff9d2b7255 start + 1
```

### PR DESCRIPTION
**Pull request by leira**
Fixes #1051

### CODE REVIEW

**Comment by doppioandante** [comment]
I wonder if a regression test makes more sense than unit test here.

**Comment by leira** [comment]
Oh, yes, these tests, let me figure out how to add one.

**Comment by leira** [comment]
I tried to put
```
echo -debug %opt{ui_options}
```
in a cmd file, and run the test, but it didn't crash. While `kak -n -q -e 'set -debug %opt{ui_options}'` crashes everytime on my Mac.

Well, the fix is quite self explained, I can remove the unit test.

**Comment by lenormf** [comment]
Using `ui_options` as a repro case isn't a good idea, as this variable will almost certainly be set. According to the bug report, using a newly declare variable initialized with an empty string should trigger the issue right?

**Comment by mawww** [comment]
I'd prefer a regression test for that, in test/regression/1051-crash-on-empty-param

**Comment by leira** [comment]
I tried all kinds of combination, using exist empty options, declared new test options, but couldn't reproduce it in regression test.

The change itself is self explained enough, I removed the unit test. I don't think I should waste any more time on this change.

**Pull request merged**
