### PR TITLE
github: Add a template for bug reports

### PR DESCRIPTION
**Pull request by lenormf**
Demo issue at #1707.

I constantly follow the same format when I report an issue, making use of github's templates could save us some time as the same questions often come back when investigating a bug.

HTH.

### CODE REVIEW

**Comment by lenormf** [comment]
Any thoughts? Does the template make issues look too scary?

**Comment by Delapouite** [comment]
I feel this PR belongs to the same bucket that:

better wiki engine: https://github.com/mawww/kakoune/issues/1472
kakoune github org: https://github.com/mawww/kakoune/issues/1606

The kakoune community is *microscopic* (even counting its 3000 stars). And there's no real need for big guns to handle the small stream of questions and contributions.

Now we could talk about the project's vision for the future, but it may deserve a dedicated conversation.

**Comment by lenormf** [comment]
It doesn't matter how many users report bugs, the problem is that new users don't know what information to include in their issues.

**Comment by mawww** [comment]
I am not sure we need such a template, I am afraid it will draw away some reports due to the apparent difficulty to get all the informations requested (like, whats my kakoune version, I installed it through the package manager of my distribution).

I think a simpler template, close to what @nochiel usually uses, like https://github.com/mawww/kakoune/issues/1718 would be better.

**Comment by lenormf** [comment]
The only difference is the last section, which contains a checklist and info that is almost always needed. I could remove it to make the issue look more like the one you like, but then it would be pointless to have a template if all there is in it is sections that could be merged into a single sentence.

I could turn the template into a generic quote, giving a list of pieces of data that could potentially be of interest, the layout of the issue would be free.

**Comment by lenormf** [comment]
I edited the template, it should now only show three sections, but has comments to guide users.

**Pull request merged**
