### PR TITLE
Python: Highlight docstrings with documentation face, not string.

### PR DESCRIPTION
**Pull request by m-kru**
Issue https://github.com/mawww/kakoune/issues/3857

### CODE REVIEW

**Comment by lenormf** [comment]
Why not use the `documentation` face?

**Comment by m-kru** [comment]
True. But there is another issue. It breaks tests for
```
add-highlighter shared/python/docstring/ region '>>> \K'    '\z' ref python
add-highlighter shared/python/docstring/ region '\.\.\. \K'    '\z' ref python
```
image

**Comment by m-kru** [comment]
@mawww I see you merged this, but it has broken tests.

**Comment by lenormf** [comment]
It also uses the `comment` face. Please don't forget to write `Closes #3857` in the commit of your follow-up PR, for archiving purposes and to allow Github to close the ticket automatically.

**Comment by m-kru** [comment]
@lenormf The `comment` face has been changed to the `documentation` face. Nevertheless, I still do not understand why this PR has been merged as it breaks tests.

**Comment by m-kru** [comment]
Ok, the face has not been changed. I forgot to push the change. But stil, why it has been merged?

**Comment by lenormf** [comment]
Thanks for the change. It's just an oversight, no harm done as long as no release is being made. You can amend changes in subsequent PRs.

**Comment by mawww** [comment]
missed the broken tests when I merged, we can fix that in an upcoming PR.

**Comment by m-kru** [comment]
It should be noted somewhere so that this is not missed.

**Comment by mawww** [comment]
Fixed.

**Comment by m-kru** [comment]
@mawww it requires yet another small fix. I have prepared PR https://github.com/mawww/kakoune/pull/3906.

**Pull request merged**
