### PR TITLE
Empty the `mimetype` variable of buffers with a static extension

### PR DESCRIPTION
**Pull request by lenormf**
Hi,

Got tired of setting `filetype` manually when opening some files, so here you go. Details in the commit.

HTH.

### CODE REVIEW

**Comment by lenormf** [comment]
How we doing in here?

**Comment by lenormf** [comment]
RFC!

**Comment by mawww** [comment]
I'd like to do a general cleanup of filetype detection, between `file` command, extensions based detection, shebang detection...

What we have currently is pretty messy, hard to predict, and we are using hacks to tie it all together (like setting mimetype to an empty value).

We should have a well defined detection sequence, thats predictible and clean, this PR goes further into the hacks I'd like to get rid of.

**Comment by lenormf** [comment]
I understand, what do you plan on replacing all that with?

However, in the mean time this PR is needed for files that contain code from different languages, so users still don't have proper filetype detection by default without it.

**Comment by casimir** [comment]
I don't know if it's the same root cause but I just had a 300 loc python file with a filetype set as `cpp`.

**Comment by lenormf** [comment]
That's `file` shitting the bed. And since the extension doesn't have the priority over the mimetype (which this PR fixes), if `file` is wrong, then you end up with a wrong filetype.

**Comment by mawww** [comment]
I wonder in what cases the `file` command is really useful now, I think we are at a point where it does more harm than good, and we could just get rid of `mimetype` simplifying all filetype scripts. At least, we should change the logic so that `file` is just a fallback, and that should not require dirty hacks like setting mimetype to empty.

**Comment by lenormf** [comment]
Mimetypes are very handy when opening files that don't have extensions, they are a good compliment to hooks that check file extensions, e.g. when downloading and editing a pastebin (you just get a raw file).

**Comment by lenormf** [comment]
Superseeded by #949.

**Pull request closed without merging**
