### PR TITLE
Add a dedicated documentation page about scopes

### PR DESCRIPTION
**Pull request by lenormf**
Hi,

I feel like the documentation could use a dedicated page about scopes, so here it is.

I also want to specify what scopes some variables/hooks are ignored in certain contexts, but it's going to need more work.

### CODE REVIEW

**Comment by Delapouite** [comment]
Thanks for this page.
It clarifies things for me. I never paid pay too much attention to scopes yet, but intuitively I thought that the buffer scope had priority over the window one, but it appears it's the other way around.

**Comment by mawww** [comment]
Looks good to me, any other changes you want to make before merging ?

**Comment by lenormf** [comment]
Yes I wanted to talk about the reach of the hooks, but I think a simple line who be enough given their names (e.g. the `BufWrite` buffers don't consider the `window` scope because they are buffer related actions).

**Comment by lenormf** [comment]
I think that's all, should be ready for review/merge.

**Pull request merged**
