### PR TITLE
Add some regex to parse c-family numbers

### PR DESCRIPTION
**Pull request by angt**
Better but still not perfect.

### CODE REVIEW

**Comment by jedisct1** [comment]
I agree that the current regex is way too permissive.

Highlighting is really useful in order to spot typos and other syntax errors, and the current regex will let them slip through.

This pull request seems to work fine for me. It would be nice to consider its inclusion.

**Comment by lenormf** [comment]
I wrote a regex to highlight numbers in the [D support script](https://github.com/mawww/kakoune/blob/master/rc/dlang.kak#L33), and I faced the same dilemma: do we want to keep the regex as simple as possible but potentially have mismatches ? Or do we make the regex engine work more but have a stricter rule on what values are actually numbers ?

Like @mawww, I think there's very little benefit from lining up the most accurate regular expressions, as what we want to match are *just* numbers. Simpler -although more error prone- regular expressions will keep highlighting coherent and the load on the regex matcher lighter.

**Comment by mawww** [comment]
I do not oppose more strict number matching, but I think 5 new expressions is too much, we should compact that, and the current commit keeps the existing regex which defeat the purpose.

**Comment by jedisct1** [comment]
They can be condensed into a single expression, but it will greatly impact readability.

**Comment by mawww** [comment]
Does not need to be a single one, I'd be ok with one integer regex and one floating point regex

**Comment by mawww** [comment]
This is pretty out of date, closing.

**Pull request closed without merging**
