### PR TITLE
Rename ModuleLoad hook

### PR DESCRIPTION
**Pull request by codesoap**
With this pull request I intend to clarify the exact time, when the hook is executed. When I first encountered the hook it was unclear to me, whether it's run before or after a module is loaded.

See #2991.

### CODE REVIEW

**Comment by lenormf** [comment]
Could you please remove all those empty merge commits, to have just your last one commit on top of `master`?

**Comment by codesoap** [comment]
@lenormf Done. Not sure where they all came from...

**Comment by mawww** [comment]
I dont think I have a copyright waiver commit from you yet, could you add one (as this change is almost non-trivial).

**Comment by codesoap** [comment]
I hadn't come across the `CONTRIBUTING` file yet. I need to read documentation more...

**Pull request merged**
