### PR TITLE
Added an option for vertical menu layout

### PR DESCRIPTION
**Pull request by laelath**
This is the same pull request as #2212, but from a different branch so the branch name reflects the changes made.

### CODE REVIEW

**Comment by mawww** [comment]
Hi, still did not get to review that and trying it, I'd like to experiment a bit with it to see if I think its an improvement or not, I'd be interested in feedback from other users as well. As said on the previous PR, I try to avoid adding options to control such behaviours, I'd rather have a single way menu are displayed and avoid the combinatorial complexity that an option would add (like bugs only happening with vertical layout menu combined with status on top and mouse disabled...)

**Comment by maximbaz** [comment]
#2199 and #2122 both have some upvotes, those should be counted as supporting this idea 😉 

There wasn't any explicit comment yet against this proposal — to everyone, if you cannot stand vertical layout, now is the time to raise your concerns.

**Comment by lenormf** [comment]
The direction of the menus isn't (probably?) such a big deal that it warrants creating an option for it. If it's an improvement, or if it's more consistent with what users expect (shell completion menus), or if nobody really cares in which direction menus are rendered, let's just switch over completely.

The issue with that being that if the majority of users who don't actively participate in discussions about development doesn't like it or finds an issue that we didn't think of, we'll have to revert the changes back, which is always confusing for users who don't re-compile the development version regularly.

**Comment by laelath** [comment]
There is a slight inconsistency in that the scroll bar is still vertical, but the columns appear to scroll sideways. Not sure how important this is though.

**Comment by laelath** [comment]
I've removed the option and switching logic now, so this branch can get merged if it gets decided to go with vertical menus.

**Comment by maximbaz** [comment]
@mawww have you had a chance to try this PR out?

**Comment by laelath** [comment]
I've rebased against the latest master, seems to still work perfectly.

**Comment by maximbaz** [comment]
Woohoo, thanks for merging!

**Pull request merged**
