### PR TITLE
Add a variant of clippy with a santa hat

### PR DESCRIPTION
**Pull request by occivink**
Appears by default during December instead of the regular clippy, and
can be controlled with the new ui option 'ncurses_assistant_festive".
Adding a hat to the cat and Dilbert is left as an exercise.

### CODE REVIEW

**Comment by occivink** [comment]
Suggestions on how to improve the hat are welcome too, of course

**Comment by andreyorst** [comment]
I'll just leave [this](https://github.com/microsoft/vscode/issues/87268) here. Not that I'm supporting such reoprts or against those, but it seems that such change can be not a welcomed one.

**Comment by lenormf** [comment]
There's a fairly high chance that #87268 was a (successful) trolling attempt.

But this change singles-out one religious holiday, and nowadays that's potentially a bad thing no matter how innocent the original motivations were ("why Christmas and not XXX?", "this makes me feel unwelcome", "genocide" etc).

The patch also adds an option that has no practical use, it would be a double standard to merge that when we refuse all year round new options to users who want to customize actual features.

**Comment by andreyorst** [comment]
> The patch also adds an option that has no practical use, it would be a double standard to merge that when we refuse all year round new options to users who want to customize actual features.

*This is why we can't have ni.. Oh, wait, that's actually prevents bloating*

**Comment by occivink** [comment]
It's been decided that, while cute, the santa hat is a superfluous addition, so I'm closing this.

**Pull request closed without merging**
