### PR TITLE
Add aliases for rename-buffer and rename-session

### PR DESCRIPTION
**Pull request by alexherbo2**
Completes alias for rename-client

### CODE REVIEW

**Comment by lenormf** [comment]
`rename-session` is already complete-able easily when typing `:rs<tab>`, that's one more stroke than `:ns<ret>`. Only one more tabulation for `rename-buffer`, because another command is suggested as first candidate.

Why those specific aliases, too? I'm assuming they stand for "name session/client", but that goes against the name pattern of built-in commands (in which case you'd generally use fuzzy matching as above), and those aliases are not Vim ones either (to provide some sort of transitional API from one to the other).

**Comment by alexherbo2** [comment]
`rename-client` has an alias on `nc`.

**Comment by lenormf** [comment]
I see that this was introduced in 8aaeaa3187aa6cda3f2b264d474f15b4486c44b5 (6 years ago). The topic should probably have been discussed when the command names were normalised (I can't find the issue, only this commit dcd733e5fab9016afbf9d8b5c5774053c1ce24af), but it's possible that it was and the decision turned out to be not to remove anything, only add.

Regardless, if anything I think we should *remove* this alias rather than assign one to all renaming commands, unless you have pragmatic reasons to do otherwise?

**Comment by mawww** [comment]
Agreed with lenormf, I'd rather remove the "nc" alias.

**Pull request closed without merging**
