### PR TITLE
Add `-group <lang>-highlight` to highlighters

### LINKED ISSUE #814: Move all highlighters to event groups `<lang>-highlight`
@mawww on IRC:

> 13:16 < mawww> its actually pretty simple, we just need to go through all filetype support files, and add a '-group <lang>-highlight' switch to the hook adding/removing highlighting

### PR DESCRIPTION
**Pull request by greduan**
Closes #814, this makes it easy to disable all highlighting with just `set global disabled_hooks '.+-highlight'`.

Note, this PR is still WIP, as denoted by the `todo` file, there are still files I want to do stuff with before merging this PR.

In the meanwhile, the PR is open for review, in case people want to fix any errors.

### CODE REVIEW

**Comment by mawww** [comment]
I'd prefer that branch to be rebased and squashed, ideally it would be a single commit along with another empty copyright waiver one (see the CONTRIBUTING file). It seems thats a single logical change, so a single commit would make more sense in my view.

**Comment by greduan** [comment]
@mawww ready. :)

**Comment by lenormf** [comment]
A couple things:
* why rename the ini higlighter ?
* the waiver message is cut in half
* there's still a merge commit (the point of rebasing on `master` is to avoid those)

**Comment by mawww** [comment]
Hum, I realized that various 'rmhl' were still missing, among many others in scala.kak, removing highlighters should also be in its own hook, in the <lang>-highlight group.

Also, dont merge the branch yourself, I'll merge the pull request into master.

**Comment by greduan** [comment]
OK so I will close this PR and open a new one with the non-`master` branch, so as to not have to merge into master.

**Pull request closed without merging**
