### PR TITLE
src: Update the macro register after each keypress

### PR DESCRIPTION
**Pull request by lenormf**

### CODE REVIEW

**Comment by mawww** [comment]
Whats the goal there ? If its for displaying the keys being recorded, I think a hard coded behaviour in `generate_context_info` showing the keys in `recording (<reg>=<keys>...)` would be good enough.

**Comment by lenormf** [comment]
I don't care much for the issue, having the register up-to-date at any point in time makes more sense if it doesn't introduce new issues.

**Comment by mawww** [comment]
We are recording, it seems to make as much sense to consider the register should be updated once we finish recording than update it on the go. This is why I wonder if we have a use case for that feature, or if some behaviour gets better once we do that.

**Comment by lenormf** [comment]
One possible case would be the issue linked to this PR, I don't have any personal motivation to have that merged otherwise.

**Comment by mawww** [comment]
Reopen if we have a proper reason to do that, for now lets keep things simple.

**Pull request closed without merging**
