### PR TITLE
src: Select the data inserted by `!` and <a-!>

### LINKED ISSUE #1468: Select the data inserted by the `!` and `<a-!>` primitives
Hi,

It would be convenient to have the text inserted by the `!` and `<a-!>` primitives automatically selected after they've been added to the buffer.

Thanks.

### PR DESCRIPTION
**Pull request by lenormf**
Closes #1468

### CODE REVIEW

**Comment by aver-d** [comment]
I've tested this patch for a few months. It works nicely, thanks.

The main advantage is being able to immediately press `s` to select inside the newly inserted text, and it's also useful for moving the entire text for alignment or indentation.

**Comment by aver-d** [comment]
I forgot to mention that I've noticed that when the command returns no output or has an error (eg. `! printf <ret>` or `!unknown-cmd <ret>` ), then the selection extends upwards towards the first character in the buffer.

I typically use `!` programmatically inside scripts, so this has not come up much for me, but I suppose in the case of an error I'd expect no change in the current selection. Maybe an error message would be useful too.

**Comment by lenormf** [comment]
I think I see where the problem is, I'll look into it.

**Comment by lenormf** [comment]
Updated the documentation.

**Comment by lenormf** [comment]
Rebased on master.

**Pull request closed without merging**
