### PR TITLE
src: Select the data inserted by `!` and `<a-!>`

### LINKED ISSUE #1468: Select the data inserted by the `!` and `<a-!>` primitives
Hi,

It would be convenient to have the text inserted by the `!` and `<a-!>` primitives automatically selected after they've been added to the buffer.

Thanks.

### PR DESCRIPTION
**Pull request by lenormf**
Closes #1468

### CODE REVIEW

**Comment by krobelus** [comment]
I've been using this for a bit, it feels nice.
It's a minor breaking change, maybe we should do the same for `p` and `P` right away. Does anyone have an implementation of https://github.com/mawww/kakoune/issues/4277 so we can try both for a while?

**Comment by mawww** [comment]
I am working on a refactoring of selections insert/replace that should make implementing this much cleaner, I do agree with this change (and the p/P one) but want to finish my refactoring first.

**Comment by lenormf** [comment]
Rebased on master.

**Comment by Delapouite** [comment]
I intend to merge this, I just want to make a release before going into various breaking changes

As a release has been done a couple of weeks after the last message (https://github.com/mawww/kakoune/releases/tag/v2021.11.08), should this PR be merged now?

**Pull request closed without merging**
