### PR TITLE
rc/tools/git add cat-file

### PR DESCRIPTION
**Pull request by QiBaobin**
Support check out current file content in another branch/commit, like: 
`git cat-file blob ohter-branch:<c-r>%`

### CODE REVIEW

**Comment by mawww** [comment]
`cat-file` does not strike me as something that is very regularly used, could you at least describe the use case you have for it ?

**Comment by QiBaobin** [comment]
I don't use it a lot either, my use case is that I want checkout a file content in another commit, it's similar with using Gread in vim-fugitive.

**Comment by krobelus** [comment]
I use `git show origin/master:path/to/file` for that

**Comment by QiBaobin** [comment]
Good to know, thanks! Let me close this then.

**Pull request closed without merging**
