### PR TITLE
Translated webpage to Hungarian

### PR DESCRIPTION
**Pull request by notramo**

### CODE REVIEW

**Comment by lenormf** [comment]
Thanks for that, could you append "Closes #2354" to your commit message please?

**Comment by lenormf** [comment]
Also you mentioned that the `õ` character isn't rendered by the font, but I don't see this character used anywhere, did you remove it? Do I need to fix this bug?

**Comment by notramo** [comment]
It isn't the character I mentioned.
I assume you have searched for `õ U+00F5 LATIN SMALL LETTER O WITH `**`TILDE`** but I noticed that `ő U+0151 LATIN SMALL LETTER O WITH `**`DOUBLE ACUTE`** doesn't render properly (and also `ű U+0171 LATIN SMALL LETTER U WITH DOUBLE ACUTE`).
image

**Comment by lenormf** [comment]
Could you please open an issue, so we don't forget about it?

**Comment by lenormf** [comment]
Could you also add the following to your PR (seperate commit, or amended, whichever):

```diff
diff --git a/js/translate.js b/js/translate.js
index ad37798d..d0de4f54 100644
--- a/js/translate.js
+++ b/js/translate.js
@@ -19,6 +19,7 @@
             "navbar:translation": "Traduction",
             "navbar:translation:english": "Anglais",
             "navbar:translation:french": "Français",
+            "navbar:translation:hungarian": "Hongrois",
 
             "banner:title": "Kakoune : l'éditeur de code",
             "banner:pitch": "Editeur modal · Plus rapide via moins de touches · Sélections multiples · Conception orthogonale",
```

**Comment by lenormf** [comment]
Depends on #2534.

**Comment by notramo** [comment]
@lenormf I added the line.

**Pull request merged**
