### PR TITLE
Fix setext-style markdown header highlight

### PR DESCRIPTION
**Pull request by pickfire**
Reproduce:

```markdown
- item

header
------
```

### CODE REVIEW

**Comment by Screwtapello** [comment]
What happens in a situation like this?

```
abcdef
ghijkl
------
```

I think headings require `\n\n` to ensure there is a blank line before the heading text. I'm not sure why headings need *three* newlines after a bulleted-list, though.

**Comment by pickfire** [comment]
@Screwtapello That will still highlight the header but the non header won't be highlighted.

I also found that this does not work.

```
three
---

four
---
```

I believe https://github.com/mawww/kakoune/blob/09a45a2e964e1efb39335926b2b88ce71e460ee4/rc/filetype/markdown.kak#L62 is probably wrong, commenting that affects the header.

**Comment by pickfire** [comment]
@Screwtapello I sent a fix for the issue you mentioned.

**Comment by Screwtapello** [comment]
I haven't tested your change yet, but it looks much better!

**Comment by pickfire** [comment]
How should one add tests for highlighting? I don't find it a simple task to test out highlighting.

**Pull request merged**
