### PR TITLE
"Fewer"

### PR DESCRIPTION
**Pull request by joshthewebgeek**
https://www.youtube.com/watch?v=UJPeg1b-jVo

### CODE REVIEW

**Comment by lenormf** [comment]
Could you make the same change on the `gh-pages` branch, which hosts http://kakoune.org/ ?

**Comment by joshthewebgeek** [comment]
Good idea. [Done.](https://github.com/mawww/kakoune/pull/981)

**Comment by lenormf** [comment]
Thanks!

**Comment by mawww** [comment]
According to https://en.wikipedia.org/wiki/Fewer_vs._less it does not look like fewer is clearly more correct, and that less has been used with countable objects for a very long time in the English language.

That said, I dont mind much, if people really feel fewer is better, I can merge that, I expect everybody to understand both words.

**Comment by mawww** [comment]
No activity on that, I'll take it as no strong support for Fewer rather that Less.

**Pull request closed without merging**
