### PR TITLE
make wording more explicit about autoloaded files

### PR DESCRIPTION
**Pull request by flavius**

### CODE REVIEW

**Comment by alexherbo2** [comment]
+1 for `.kak` file specification.

But ‹ recursively source […] files matching `$XDG_CONFIG_HOME/kak/autoload/*.kak` › is confusing; ‹ recursively source […] files in `$XDG_CONFIG_HOME/kak/autoload` › was better.

**Comment by lenormf** [comment]
The tree needs to be rebased on `master`, something's wrong with the history shown by github.

**Comment by mawww** [comment]
Can you cleanup the history for this branch, it should get rebased on current master and only contains the relevant commits.

**Comment by mawww** [comment]
Autoloading documentation has been reworked, closing.

**Pull request closed without merging**
