### PR TITLE
Update spec file to the new release

### PR DESCRIPTION
**Pull request by jkonecny12**
Thanks spacekookie for pointing this out :)

### CODE REVIEW

**Comment by jkonecny12** [comment]
Maybe we should think about a script (Makefile) to make a new release and update all these files automatically on a release.

**Comment by lenormf** [comment]
Isn't there an official package by now? The project can't maintain this kind of files forever now that several official releases have been produced, users will almost constantly be out of date.

**Comment by jkonecny12** [comment]
Sadly it is not. It is on my TODO list but I have it a little bit bigger... :(

**Comment by jkonecny12** [comment]
I will try to make it a priority and keep this file up to date.

**Comment by lenormf** [comment]
Thanks, it would be really convenient to distribute the work load!

**Pull request merged**
