### PR TITLE
Add git next-hunk and prev-hunk commands

### LINKED ISSUE #2423: Implement `git` commands to jump to the previous/next modification in the buffer
Hi,

It'd be nice to have commands that jump from one hunk to the other, whose lines can already be highlighted with the `:git show-diff` command.

However I think it'd also be better if users didn't have to use `show-diff` in order to be able to jump to a hunk (to make use of the flag option that stores line coordinates), so some kind of refactoring would potentially have to take place.

HTH.

### PR DESCRIPTION
**Pull request by Anfid**
Fixes #2423 
Alternative implementation #2458

### CODE REVIEW

**Comment by lenormf** [comment]
Why reimplement the feature? The code is essentially the same, except you have one function that does two loops and stores data in an option?

**Comment by Anfid** [comment]
That MR was not updated for a long time and my solution provides a more efficient implementation, that also addresses mawww's notes

**Comment by lenormf** [comment]
It's not clear to me how it's more efficient, could you explain?

**Comment by Anfid** [comment]
All hunks are cached into separate list, that contains only single line number for each hunk. This prevents unnecessary iterations on larger hunks. After that, if no changes to the buffer were made, this function only operates on smaller list.

This also corresponds to regular workflow, alternating between edit and navigation.

**Comment by lenormf** [comment]
I see. It's specifically the caching part that I'm sceptical about. It's not uncommon for me to run linting on several long files at the same time, having persistent storage whose size is proportional to the amount of diagnostics just for jumping across them is not appealing.

**Comment by Anfid** [comment]
I'm not sure, what linting on large files has to do with this storage. It only stores one number for each hunk, even if it consists of multiple lines. If you don't use any of these commands, then it won't be generated for this buffer and no extra memory will be used. And considering some changes to file, that is somewhat like 4 bytes per hunk. I feel like ~40 bytes per buffer with medium size diff is worth it to save some cpu cycles. I don't see a problem here. But if you do have a more concrete problem in mind, we could discuss alternative solution

**Comment by lenormf** [comment]
#3321

**Pull request merged**
