### PR TITLE
make: use 'info' instead of 'echo'

### PR DESCRIPTION
**Pull request by occivink**
The message is much more prominent this way.
In addition, remove leading whitespace from the message.

### CODE REVIEW

**Comment by mawww** [comment]
I am wondering about this, as it will display on top of the buffer. I am not sure we gain much by moving from the status line to an info box.

**Comment by occivink** [comment]
I personally prefer it but maybe we can get some other opinions on this?

**Comment by lenormf** [comment]
I don't care for UI messages much, and would send them to the `*debug*` buffer if I could, as this is the first place I would look if the expected side effects for a command haven't visibly occurred.

I could also see a user sending all messages to a `*notifications*` buffer as well, to keep them within eyesight in a pane, but not letting them pollute the main pane.

Since we now have three different preferences regarding those, maybe a hook/option could be added that is in charge of delivering notifications, defaulting to `echo` if undefined?

**Comment by Delapouite** [comment]
> maybe a hook/option could be added that is in charge of delivering notifications, defaulting to echo if undefined

Yes that's would be a nice way to handle it, a hook letting users decide what to do when a message is about to displayed with `echo`, `info`…

**Comment by occivink** [comment]
Closing, as it seems to be a matter of preference

**Pull request closed without merging**
