### PR TITLE
Solarized light

### PR DESCRIPTION
**Pull request by stevenyvr987**
Here is a simple PR to add a solarized light color theme to the existing dark theme. This updates my previous PR #1391, which I'm closing.

### CODE REVIEW

**Comment by lenormf** [comment]
There are weird hunks in the original solarized file, which modify some whitespace, and those have apparently been mirrored onto the new file which results in wonky alignment.

**Comment by lenormf** [comment]
Use github to open the files in this PR in "raw" mode, you'll see that things are mis-aligned. You might have to do some `%@` in the buffers.

**Comment by stevenyvr987** [comment]
The files are as intended; there are no mixed uses of tabs and whitespaces. The irregular leading spaces in some of the lines are a side effect of my intention to vertcally align the rgb values so that they can be easily checked by eye against each other and against the corresponding values listed in the solarized website.

**Comment by lenormf** [comment]
Ok, I wasn't looking at things that way.

**Comment by Delapouite** [comment]
Thanks for your contribution @stevenyvr987 

I tried to use your solarized_light colorscheme. and I had some trouble. My terminal is in dracula (https://draculatheme.com/), and you did not redefine all the colors. So in the end I have a broken mix of dracula and solarized color.

For example:
```
face PrimarySelection   white,blue
```
should be:
```
face PrimarySelection   ${base03},${blue}
```
and so on…

**Comment by stevenyvr987** [comment]
@Delapouite sorry for the delayed response, I saw your message just now.

I think you've identified a shortcoming with the original solarized.kak file: some of the face def'ns have hard-coded the colors black and white, but like you pointed out they should use base03 and maybe base0, respectively. Also, I think that the faces using default+b should maybe use a base color combination instead.

Let me wrap my head around this a bit longer and later submit a corrective commit.

**Comment by Delapouite** [comment]
yes, some work may need to be done to the original solarized (dark)

**Comment by bhajneet** [comment]
I made these fixes in #1627

**Pull request closed without merging**
