### PR TITLE
website: add link to discuss.kakoune.com in navbar

### PR DESCRIPTION
**Pull request by Delapouite**
Despite the small size of our community, I think that the initiative launched by @robertmeta has proven successful with already many interesting bits of shared knowledge about kakoune.

Those links will further increase the visibility of this discussion board for new comers seeking help.

### CODE REVIEW

**Comment by lenormf** [comment]
As this is not an official media, I'd rather we put the link into a "Community" dropdown. We could also put the Wiki link into that same dropdown menu.

**Comment by Delapouite** [comment]
As this is not an official media

mawww is participating on it. By hiding it behind a dropdown, it complicates discoverability

**Comment by lenormf** [comment]
It's being maintained by a member of the community, making it a community site.

Also when more sites ever pop-up (btw there's a sub-reddit that could be added to the list as well), we'll need to group them together, as we can't have all of them occupy a full item in the navbar.

**Comment by robertmeta** [comment]
@lenormf what changes would in your mind transition it from community maintained to a more official place?  Mawww is already an admin on the site (I would welcome you as one as well if interested).  I can setup the domain and any resources that are applicable to fall to @mawww in a pinch.  

I think it is important to pick one among the many sites to be the heart of the **user** community.  I think this is important for the growth of Kakoune among users.  I have been a moderator of the #vim channel on freenode for going on two decades, as well recently (last few years) the vim subreddit.  While I love both of those mediums, I think both make a poor heart of a community due to various things they lack, from topic splitting to mailing list mode to time-shifting.

**Comment by robertmeta** [comment]
@lenormf thank you for your clarification, I don't find it particularly compelling but I appreciate you making your POV clear.

**Comment by mawww** [comment]
I do not have a strong opinion on that menu, both options are fine by me, and I'd rather not have to make an arbitrary decision.

In general I would tend to favor a "self organizing community", in the sense that I dont think I should bless anything in particular, I try to follow discuss, reddit, irc... Thinking of it, I might have a preference for the community menu as we can add links to all of those (irc in particular).

**Pull request closed without merging**
