### PR TITLE
rc: add gdscript.kak

### PR DESCRIPTION
**Pull request by kkga**
This adds filetype support for [Godot](https://godotengine.org) engine's GDScript language.

### CODE REVIEW

**Comment by lenormf** [comment]
Feel free to create a PR to [kakoune-extra-filetypes](https://github.com/kakoune-editor/kakoune-extra-filetypes) if this doesn't get merged.

**Comment by kkga** [comment]
> Feel free to create a PR to [kakoune-extra-filetypes](https://github.com/kakoune-editor/kakoune-extra-filetypes) if this doesn't get merged.

Thanks for letting me know.

Do you have an idea of what are the chances of this getting merged?

Probably wouldn't hurt to submit a PR to the mentioned repo in either case.

**Comment by lenormf** [comment]
Good chances, but if it doesn't happen, you have an alternative.

@mawww let's merge this!

**Comment by lenormf** [comment]
To anybody who would like to further improve the script, feel free to address the issues pointed at https://github.com/kakoune-editor/kakoune-extra-filetypes/pull/8

**Pull request merged**
