### PR TITLE
Documentation additions

### PR DESCRIPTION
**Pull request by danr**

### CODE REVIEW

**Comment by danr** [comment]
I added some more documentation improvements to the PR (Accidentally! I force pushed to my fork, and that made github also change this PR... Confusing.) 

Thanks,
Dan

**Comment by mawww** [comment]
And could you add a copyright waiver commit as well (see the CONTRIBUTING file).

Thanks a lot for the pull request.

**Comment by doppioandante** [comment]
@danr do you mind if I finish your pull request?

**Comment by lenormf** [comment]
Are we sure those changes are still relevant ?

**Comment by doppioandante** [comment]
@lenormf you're right, this is not needed anymore

**Pull request closed without merging**
